window.K8S_CONTENT_EN = window.K8S_CONTENT_EN || {};
window.K8S_CONTENT_EN['fluxcd/fluxcd-fundamentals'] = {
  theory: `
# FluxCD & GitOps Fundamentals

## Relevance
FluxCD is the reference implementation of GitOps for Kubernetes — a CNCF Graduated project. GitOps uses Git as the single source of truth for all infrastructure and applications. Flux monitors Git/Helm/OCI repositories and automatically reconciles the cluster to the desired state. It is the foundation of modern continuous delivery platforms.

## Core Concepts

### What is GitOps?

\`\`\`
GitOps Principles (OpenGitOps):

1. Declarative
   The entire desired state is described declaratively
   (YAML manifests, Helm values, Kustomize overlays)

2. Versioned and Immutable
   Desired state stored in a versioned way (Git)
   Each change is an auditable commit

3. Pulled Automatically
   SOFTWARE agents pull state from Git
   NOT push — the cluster pulls, doesn't receive push

4. Continuously Reconciled
   Agents ensure actual state = desired state
   Automatically detect and fix drift
\`\`\`

### FluxCD Architecture

\`\`\`
Git Repository (GitHub/GitLab/Gitea)
         │
         │ PULL (polling)
         ▼
┌─────────────────────────────────────────┐
│              Flux Controllers            │
│                                          │
│  ┌──────────────────────────────────┐   │
│  │ source-controller                │   │
│  │ Monitors: Git, Helm, OCI, Bucket │   │
│  └──────────────────┬───────────────┘   │
│                     │ Artifact          │
│  ┌──────────────────▼───────────────┐   │
│  │ kustomize-controller             │   │
│  │ Applies: Kustomizations          │   │
│  └──────────────────────────────────┘   │
│  ┌──────────────────────────────────┐   │
│  │ helm-controller                  │   │
│  │ Applies: HelmReleases            │   │
│  └──────────────────────────────────┘   │
│  ┌──────────────────────────────────┐   │
│  │ notification-controller          │   │
│  │ Alerts: Slack, PagerDuty, etc.   │   │
│  └──────────────────────────────────┘   │
│  ┌──────────────────────────────────┐   │
│  │ image-reflector-controller       │   │
│  │ Detects: new registry images     │   │
│  └──────────────────────────────────┘   │
│  ┌──────────────────────────────────┐   │
│  │ image-automation-controller      │   │
│  │ Updates: manifests with new img  │   │
│  └──────────────────────────────────┘   │
└─────────────────────────────────────────┘
         │
         │ kubectl apply
         ▼
    Kubernetes Cluster
\`\`\`

### Main Flux CRDs

\`\`\`
Source Controller:
├── GitRepository      — monitors Git repository
├── HelmRepository     — monitors Helm repository (index.yaml)
├── HelmChart          — specific chart from a HelmRepository
├── OCIRepository      — monitors OCI registry (images/artifacts)
└── Bucket             — monitors S3/GCS/Azure Blob

Kustomize Controller:
└── Kustomization      — applies manifests/kustomize to cluster

Helm Controller:
└── HelmRelease        — Helm chart deployment

Notification Controller:
├── Provider           — notification destination (Slack, Teams, etc.)
├── Alert              — rule for when and what to notify
└── Receiver           — webhook to receive external events

Image Automation:
├── ImageRepository    — monitors registry for new tags
├── ImagePolicy        — selects which tag to use (semver, regex)
└── ImageUpdateAutomation — commits image updates to Git
\`\`\`

### Flux CLI Installation and Bootstrap

\`\`\`bash
# Install Flux CLI
curl -s https://fluxcd.io/install.sh | sudo bash

# Check cluster prerequisites
flux check --pre

# Bootstrap with GitHub (installs Flux in cluster AND configures repo)
export GITHUB_TOKEN=ghp_xxxxxxxxxxxx
export GITHUB_USER=my-user

flux bootstrap github \\
  --owner=\${GITHUB_USER} \\
  --repository=fleet-infra \\
  --branch=main \\
  --path=clusters/my-cluster \\
  --personal

# For existing repository:
flux bootstrap github \\
  --owner=myorg \\
  --repository=gitops-repo \\
  --branch=main \\
  --path=clusters/production
\`\`\`

\`\`\`bash
# Bootstrap with GitLab
flux bootstrap gitlab \\
  --owner=mygroup \\
  --repository=fleet-infra \\
  --branch=main \\
  --path=clusters/production \\
  --token-auth

# Bootstrap with SSH key (for any git provider)
flux bootstrap git \\
  --url=ssh://git@github.com/myorg/fleet-infra \\
  --branch=main \\
  --path=clusters/production \\
  --ssh-key-algorithm=ecdsa
\`\`\`

### Typical Repository Structure

\`\`\`
fleet-infra/
├── clusters/
│   ├── production/
│   │   ├── flux-system/           ← Generated by bootstrap
│   │   │   ├── gotk-components.yaml
│   │   │   ├── gotk-sync.yaml
│   │   │   └── kustomization.yaml
│   │   ├── apps/
│   │   │   ├── kustomization.yaml ← Points to apps/
│   │   │   └── podinfo.yaml       ← HelmRelease or Kustomization
│   │   └── infrastructure/
│   │       ├── kustomization.yaml
│   │       └── cert-manager.yaml
│   └── staging/
│       └── flux-system/
├── apps/
│   ├── base/
│   │   └── podinfo/
│   │       ├── kustomization.yaml
│   │       ├── deployment.yaml
│   │       └── service.yaml
│   ├── production/
│   │   └── podinfo/
│   │       └── kustomization.yaml  ← Production overlay
│   └── staging/
│       └── podinfo/
│           └── kustomization.yaml  ← Staging overlay
└── infrastructure/
    ├── base/
    │   └── cert-manager/
    └── production/
\`\`\`

### GitRepository — Monitor Git

\`\`\`yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fleet-infra
  namespace: flux-system
spec:
  interval: 1m                   # Check for changes every 1 minute
  url: https://github.com/myorg/fleet-infra
  ref:
    branch: main                 # or tag: v1.0.0 or commit: abc123
  secretRef:
    name: flux-system            # Secret with SSH key or token
\`\`\`

### Kustomization — Apply Manifests

\`\`\`yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m                   # Reconcile every 5 minutes
  path: ./apps/production        # Path in Git repository
  prune: true                    # Delete resources removed from Git
  sourceRef:
    kind: GitRepository
    name: fleet-infra
  healthChecks:                  # Wait for resources to be healthy
    - apiVersion: apps/v1
      kind: Deployment
      name: podinfo
      namespace: podinfo
  postBuild:
    substitute:
      ENVIRONMENT: "production"
      DOMAIN: "acme.io"
\`\`\`

### HelmRepository and HelmRelease

\`\`\`yaml
# Helm Repository
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1h
  url: https://stefanprodan.github.io/podinfo
---
# Deploy via HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: ">=6.0.0 <7.0.0"  # Semver range
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
  values:
    replicaCount: 2
    ingress:
      enabled: true
      hosts:
        - host: podinfo.acme.io
  valuesFrom:                    # Values from ConfigMap/Secret
    - kind: ConfigMap
      name: podinfo-values
      valuesKey: values.yaml
\`\`\`

### Drift Detection and Reconciliation

\`\`\`bash
# See status of all Flux resources
flux get all

# See Kustomizations
flux get kustomizations

# See HelmReleases
flux get helmreleases

# Force immediate reconciliation
flux reconcile kustomization apps --with-source
flux reconcile helmrelease podinfo --with-source

# See controller logs
flux logs --kind=Kustomization --name=apps

# Suspend reconciliation (for maintenance)
flux suspend kustomization apps
flux resume kustomization apps
\`\`\`

### Common Mistakes

1. **interval too short** — interval: 30s increases load on Git server and cluster. For production, use 1m-5m.
2. **prune: false in production** — Without prune, resources deleted from Git remain in cluster (drift). Use prune: true carefully.
3. **Wrong path in Kustomization** — The path is relative to the root of the repository, not to local checkout.
4. **Missing auth Secret** — Private GitRepository without secretRef will fail with 401 error.
5. **Misconfigured healthChecks** — Kustomization waits for resource that doesn't exist in the path; reconciliation gets stuck.

## Killer.sh Style Challenge

> **Scenario:** Configure GitOps for an application: (1) Create a GitRepository pointing to https://github.com/stefanprodan/podinfo, branch main, interval 1m; (2) Create a Kustomization that applies the ./kustomize directory of the repository to the podinfo namespace with prune: true; (3) Verify that the application was deployed automatically.
`,
  quiz: [
    {
      question: 'What are the 4 principles of GitOps (OpenGitOps)?',
      options: [
        'Git, CI/CD, Containers, Automation',
        'Declarative, Versioned/Immutable, Pulled automatically, Continuously reconciled',
        'Push, Pull, Deploy, Monitor',
        'Source, Build, Test, Deploy'
      ],
      correct: 1,
      explanation: 'The 4 OpenGitOps principles: (1) Declarative — state described in files; (2) Versioned/Immutable — Git as source; (3) Pulled automatically — agents pull, don\'t receive push; (4) Continuously reconciled — actual state = desired state.',
      reference: 'Related concept: The "pull" model is fundamental — the agent in the cluster pulls from Git, not the CI/CD pushing to the cluster.'
    },
    {
      question: 'Which Flux controller is responsible for monitoring Git, Helm, and OCI repositories?',
      options: [
        'kustomize-controller',
        'source-controller',
        'helm-controller',
        'notification-controller'
      ],
      correct: 1,
      explanation: 'The source-controller monitors external sources: GitRepository (Git), HelmRepository (Helm index), OCIRepository (OCI registries), and Bucket (S3/GCS). It downloads artifacts and makes them available to other controllers. kustomize-controller and helm-controller CONSUME these artifacts.',
      reference: 'Related concept: source-controller creates an artifact (tarball) that other controllers reference — this decouples the download from the apply.'
    },
    {
      question: 'What happens when prune: true is configured in a Kustomization?',
      options: [
        'The namespace is deleted along with resources',
        'Resources that exist in the cluster but were removed from the Git repository are automatically deleted from the cluster',
        'All resources are recreated with each reconciliation',
        'Resources with errors are deleted and recreated'
      ],
      correct: 1,
      explanation: 'With prune: true, Flux tracks which resources were created by that Kustomization. If a resource is removed from Git (commit that deletes a file), Flux automatically deletes the corresponding resource from the cluster. With prune: false, those resources remain as orphans.',
      reference: 'Related concept: Use prune: true along with careful Git workflow — an accidental delete in the repository can delete production.'
    },
    {
      question: 'How does Flux authenticate with private Git repositories?',
      options: [
        'Using kubectl credentials',
        'Using a Secret referenced in secretRef in the GitRepository — with SSH key, token, or username/password',
        'Automatically with cluster credentials',
        'Using the flux-system ServiceAccount'
      ],
      correct: 1,
      explanation: 'Private GitRepositories need secretRef pointing to a Secret in the flux-system namespace. The Secret can have: SSH key (identity, identity.pub, known_hosts), token (username + password or bearerToken), or HTTPS with username/password. flux bootstrap automatically creates this Secret.',
      reference: 'Related concept: For GitHub Actions, use Deploy Keys (read-only) in the repository instead of personal tokens.'
    },
    {
      question: 'What does the command flux reconcile kustomization apps --with-source do?',
      options: [
        'Recreates the entire Kustomization from scratch',
        'Forces immediate reconciliation: first re-downloads the source (GitRepository) and then re-applies the Kustomization to the cluster',
        'Verifies if the Kustomization is synchronized',
        'Suspends and resumes the Kustomization'
      ],
      correct: 1,
      explanation: '--with-source first forces the Source (GitRepository) reconciliation to fetch the latest commit, then reconciles the Kustomization with that new artifact. Without --with-source, it only reconciles with the current artifact (without fetching new versions).',
      reference: 'Related concept: flux suspend and flux resume temporarily control automatic reconciliation — useful for maintenance.'
    },
    {
      question: 'What is the difference between the GitRepository interval and the Kustomization interval?',
      options: [
        'They are the same interval',
        'GitRepository.interval defines how often the source is checked (new commit?); Kustomization.interval defines how often manifests are re-applied to the cluster (even without Git changes)',
        'Kustomization.interval is always larger than GitRepository.interval',
        'Only Kustomization has interval; GitRepository uses webhooks'
      ],
      correct: 1,
      explanation: 'GitRepository.interval: Git polling frequency to detect new commits. Kustomization.interval: cluster reconciliation frequency — re-applies manifests even without Git changes (detects drift). Typical values: GitRepository=1m, Kustomization=5m-10m.',
      reference: 'Related concept: For faster reconciliation without increasing polling, configure Git webhooks to notify Flux.'
    },
    {
      question: 'What does the healthChecks field do in a Kustomization?',
      options: [
        'To check the health of Flux pods',
        'To wait for deployed resources to be healthy before marking the Kustomization as Ready — allows dependencies between Kustomizations',
        'To configure liveness probes on deployed pods',
        'To validate YAML before applying'
      ],
      correct: 1,
      explanation: 'healthChecks makes the Kustomization wait for resources to become Ready before marking itself as successful. Critical for dependencies: if Kustomization B depends on A (via dependsOn), B only runs after A is healthy. Without healthChecks, A may be marked Ready before resources are ready.',
      reference: 'Related concept: dependsOn in Kustomization creates deployment order — e.g., install cert-manager before any app that uses certificates.'
    }
  ],
  flashcards: [
    {
      front: 'What are the 5 main Flux v2 controllers?',
      back: '**source-controller**\nMonitors: GitRepository, HelmRepository,\nOCIRepository, HelmChart, Bucket\nCreates artifacts for other controllers\n\n**kustomize-controller**\nApplies Kustomizations to cluster\nSupports: Kustomize overlays, substitutions\n\n**helm-controller**\nManages HelmReleases\nInstalls/Upgrades/Rollbacks charts\n\n**notification-controller**\nSends alerts (Slack, Teams, PagerDuty)\nReceives external webhooks\n\n**image-reflector-controller**\nMonitors registries for new tags\n\n**image-automation-controller**\nCommits image updates to Git\n\n**Namespace:** flux-system\n**Installation:** flux bootstrap'
    },
    {
      front: 'Flux repository file structure',
      back: '```\nfleet-infra/\n├── clusters/\n│   ├── production/\n│   │   ├── flux-system/    ← bootstrap\n│   │   │   ├── gotk-components.yaml\n│   │   │   ├── gotk-sync.yaml\n│   │   │   └── kustomization.yaml\n│   │   ├── apps/\n│   │   │   └── kustomization.yaml\n│   │   └── infrastructure/\n│   │       └── kustomization.yaml\n│   └── staging/\n├── apps/\n│   ├── base/       ← base manifests\n│   ├── production/ ← production overlays\n│   └── staging/    ← staging overlays\n└── infrastructure/\n    ├── base/\n    └── production/\n```\nRecommended pattern from Flux documentation.'
    },
    {
      front: 'GitRepository — important fields',
      back: '```yaml\napiVersion: source.toolkit.fluxcd.io/v1\nkind: GitRepository\nmetadata:\n  name: fleet-infra\n  namespace: flux-system\nspec:\n  interval: 1m       # Polling frequency\n  url: https://github.com/org/repo\n  ref:\n    branch: main     # OR\n    tag: v1.0.0      # OR\n    semver: ">=1.0.0"\n    commit: abc123   # Specific commit\n  secretRef:\n    name: github-token  # Auth secret\n  ignore: |           # Files to ignore\n    *.md\n    docs/\n```\nStatus: flux get gitrepositories\nArtifact available at: .status.artifact'
    },
    {
      front: 'Flux Kustomization — important fields',
      back: '```yaml\napiVersion: kustomize.toolkit.fluxcd.io/v1\nkind: Kustomization\nmetadata:\n  name: apps\n  namespace: flux-system\nspec:\n  interval: 5m         # Reconcile frequency\n  path: ./apps/prod    # Path in repo\n  prune: true          # Delete removed resources\n  sourceRef:\n    kind: GitRepository\n    name: fleet-infra\n  targetNamespace: production  # Override namespace\n  dependsOn:           # Wait for these first\n    - name: infrastructure\n  healthChecks:        # Wait for Ready\n    - apiVersion: apps/v1\n      kind: Deployment\n      name: app\n      namespace: default\n  postBuild:\n    substitute:\n      KEY: value       # Variable substitution\n```'
    },
    {
      front: 'Essential Flux CLI commands',
      back: '**Overall status:**\n`flux get all`\n`flux get sources git`\n`flux get kustomizations`\n`flux get helmreleases`\n\n**Reconcile:**\n`flux reconcile source git fleet-infra`\n`flux reconcile kustomization apps --with-source`\n`flux reconcile helmrelease podinfo`\n\n**Suspend/Resume:**\n`flux suspend kustomization apps`\n`flux resume kustomization apps`\n\n**Logs:**\n`flux logs --kind=Kustomization --name=apps`\n`flux logs --all-namespaces`\n\n**Export/Diff:**\n`flux export source git fleet-infra`\n`flux diff kustomization apps`\n\n**Bootstrap:**\n`flux bootstrap github ...`\n`flux check --pre`'
    },
    {
      front: 'How does Flux detect and fix drift?',
      back: '**Drift Detection:**\nThe kustomize-controller reconciles\nevery `interval`. In each cycle:\n1. Downloads artifact from source-controller\n2. Generates manifests (kustomize build or helm)\n3. Compares with current cluster state\n4. Applies difference (kubectl apply)\n\n**Drift scenarios:**\n- Someone does kubectl edit in production\n- An operator modifies a resource\n- Resource is manually deleted\n\n**Flux reverts:**\nOn next reconciliation, desired state\n(Git) is re-applied.\n\n**How to inspect:**\n```bash\nflux diff kustomization apps\n# Shows what would be applied\n# without actually applying\n```\n\n**For temporary manual changes:**\n`flux suspend kustomization apps`\n(Pause reconciliation during maintenance)'
    }
  ],
  lab: {
    scenario: 'You will set up a complete GitOps environment using FluxCD. The goal is to use Git as the source of truth for automatic deployment of an application to the cluster.',
    objective: 'Install FluxCD, configure GitRepository and Kustomization, and verify automatic reconciliation.',
    duration: '20-25 minutes',
    steps: [
      {
        title: 'Install Flux CLI and Verify Prerequisites',
        instruction: `Configure Flux in your environment:
1. Install the Flux CLI
2. Check cluster prerequisites with flux check
3. Install Flux controllers in the cluster without bootstrap (manual mode for lab)
4. Verify all pods are Running`,
        hints: [
          'curl -s https://fluxcd.io/install.sh | sudo bash installs the CLI',
          'flux install installs controllers without needing a Git repository',
          'flux check --pre verifies if the cluster supports Flux before installing'
        ],
        solution: `\`\`\`bash
# Install Flux CLI
curl -s https://fluxcd.io/install.sh | sudo bash

# Or via brew on macOS
# brew install fluxcd/tap/flux

# Check version
flux version

# Check cluster prerequisites
flux check --pre
# Should show green checkmarks

# Install Flux in cluster (manual mode without bootstrap)
flux install \\
  --namespace=flux-system \\
  --network-policy=false    # For labs with restricted networking
\`\`\``,
        verify: `\`\`\`bash
# Verify all Flux pods running
kubectl get pods -n flux-system
# Expected: all controllers in Running state
# helm-controller-xxx
# kustomize-controller-xxx
# notification-controller-xxx
# source-controller-xxx

# Verify CRDs installed
kubectl get crds | grep toolkit.fluxcd.io | head -10
# Expected: gitrepositories, kustomizations, helmreleases, etc.

# Verify overall status
flux check
# Expected: all checks green

# Verify flux-system namespace exists
kubectl get namespace flux-system
\`\`\``
      },
      {
        title: 'Create GitRepository and Kustomization',
        instruction: `Configure Flux to monitor a public Git repository:
1. Create a GitRepository pointing to https://github.com/stefanprodan/podinfo (branch main)
2. Create a podinfo namespace
3. Create a Kustomization that applies the ./kustomize directory of the repository
4. Verify the application was automatically deployed`,
        hints: [
          'The podinfo repository is public — no secretRef needed',
          'The ./kustomize path in the podinfo repository has the manifests',
          'flux get kustomizations shows reconciliation status'
        ],
        solution: `\`\`\`bash
# Create namespace
kubectl create namespace podinfo
\`\`\`

\`\`\`yaml
# podinfo-source.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/stefanprodan/podinfo
  ref:
    branch: master
\`\`\`

\`\`\`yaml
# podinfo-kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: podinfo
\`\`\`

\`\`\`bash
kubectl apply -f podinfo-source.yaml
kubectl apply -f podinfo-kustomization.yaml
\`\`\``,
        verify: `\`\`\`bash
# Verify GitRepository being synchronized
kubectl get gitrepository podinfo -n flux-system
# Expected: READY=True, URL displayed

# See artifact details
kubectl describe gitrepository podinfo -n flux-system | grep -A5 "Artifact:"

# Verify Kustomization reconciling
flux get kustomizations
# Expected: podinfo READY=True APPLIED=True

# Verify application was deployed
kubectl get all -n podinfo
# Expected: deployment/podinfo, service/podinfo, pods Running

# Verify Flux manages the resources
kubectl get deployment podinfo -n podinfo -o yaml | grep -i "kustomize.toolkit"
# Expected: Flux labels on the resource

# Force manual reconciliation to verify
flux reconcile kustomization podinfo --with-source
\`\`\``
      },
      {
        title: 'Test Drift Detection',
        instruction: `Verify how Flux detects and fixes drift:
1. Make a manual change in the cluster (edit a resource)
2. Wait for the next reconciliation (or force with flux reconcile)
3. Verify that Flux reverted the change to the Git state
4. Use flux diff to see what would be applied`,
        hints: [
          'Editing replica count with kubectl scale is a change that Flux will revert',
          'flux diff kustomization shows what will be applied without applying it',
          'The Kustomization interval controls reconciliation frequency'
        ],
        solution: `\`\`\`bash
# See current state
kubectl get deployment podinfo -n podinfo
# Note the number of replicas

# Make manual drift — change replicas
kubectl scale deployment podinfo -n podinfo --replicas=5

# Verify change applied
kubectl get deployment podinfo -n podinfo | grep -i replicas

# Use flux diff to see what Flux would apply
flux diff kustomization podinfo
# Expected: shows replicas would be reverted to Git value

# Force reconciliation to revert drift
flux reconcile kustomization podinfo --with-source
\`\`\``,
        verify: `\`\`\`bash
# Verify replicas were reverted to Git value
kubectl get deployment podinfo -n podinfo
# Expected: REPLICAS should be at the original repository value

# Check Kustomization events (shows reconciliation history)
kubectl get events -n flux-system --field-selector involvedObject.name=podinfo
# Expected: successful reconciliation events

# See full Kustomization status
flux get kustomization podinfo
# Expected: READY=True, recent last apply

# See kustomize-controller logs to confirm
flux logs --kind=Kustomization --name=podinfo --tail=10
# Expected: manifest application logs
\`\`\``
      }
    ]
  },
  troubleshooting: [
    {
      title: 'GitRepository stays NotReady with authentication error',
      difficulty: 'easy',
      symptom: 'The GitRepository was created but stays READY=False with "failed to authenticate" error message.',
      diagnosis: `\`\`\`bash
# 1. Check GitRepository status
kubectl get gitrepository <name> -n flux-system
# Check READY and REASON columns

# 2. See detailed error message
kubectl describe gitrepository <name> -n flux-system | grep -A10 "Status:"
# Look for "Message:" in Conditions

# 3. Check if Secret exists
kubectl get secret <secret-name> -n flux-system

# 4. Check Secret format
kubectl get secret <secret-name> -n flux-system -o yaml | grep "data:"
# Check expected fields (identity, known_hosts for SSH; username, password for HTTPS)

# 5. See source-controller logs
kubectl logs -n flux-system -l app=source-controller --tail=20 | grep -i "error\\|fail"
\`\`\``,
      solution: `**Causes and solutions:**

1. **Private repository without Secret:** Add secretRef to GitRepository. For public repositories, it's not needed.

2. **Secret in wrong namespace:** The Secret must be in the same namespace as the GitRepository (usually flux-system).

3. **Wrong Secret format for SSH:**
\`\`\`bash
flux create secret git github-token \\
  --url=ssh://git@github.com/org/repo \\
  --ssh-key-algorithm=ecdsa
# Or create manually with identity + known_hosts
\`\`\`

4. **Expired token:** Personal tokens and deploy keys expire. Regenerate and update the Secret.

5. **Incorrect URL:** For SSH use \`ssh://git@github.com/org/repo\` with protocol. For HTTPS use \`https://github.com/org/repo\`.`
    },
    {
      title: 'Kustomization stuck in Reconciling state indefinitely',
      difficulty: 'medium',
      symptom: 'The Kustomization shows "Reconciling" status for a long time and never becomes Ready. Resources may or may not be created.',
      diagnosis: `\`\`\`bash
# 1. Check detailed status
kubectl describe kustomization <name> -n flux-system | grep -A15 "Status:"

# 2. Check if healthCheck is stuck
kubectl describe kustomization <name> -n flux-system | grep -A10 "Health:"
# Look for which resource is failing the healthCheck

# 3. Check resources that should be healthy
kubectl get deployment <name> -n <namespace>
# See if it's in Progressing or Error state

# 4. Check events
kubectl get events -n <namespace> --sort-by='.lastTimestamp' | tail -10

# 5. Kustomize-controller logs
kubectl logs -n flux-system -l app=kustomize-controller --tail=30 | grep -i "error\\|fail\\|health"
\`\`\``,
      solution: `**Causes and solutions:**

1. **healthChecks referencing non-existent resource:** The healthCheck points to a Deployment that doesn't exist in the path. Verify the name and namespace correspond to a real resource created by the Kustomization.

2. **Deployment with ImagePullBackOff:** The Pod can't download the image. The healthCheck waits for the Deployment to be Ready but it never is. Check kubectl describe pod and kubectl describe deployment.

3. **Stuck dependsOn:** The Kustomization depends on another that is also not Ready. Check flux get kustomizations to see which one is blocking.

4. **healthCheck timeout:** Add timeout: 5m to the Kustomization spec to avoid waiting indefinitely.

5. **Resources in Terminating state:** Resources from the previous cycle are Terminating. Wait or force finalizers: kubectl patch <resource> -p '{"metadata":{"finalizers":[]}}' --type=merge.`
    }
  ]
};
