window.K8S_CONTENT_EN = window.K8S_CONTENT_EN || {};
window.K8S_CONTENT_EN['keda/keda-advanced'] = {
  theory: `# KEDA Advanced — Production Patterns

## Exam Relevance
> Advanced KEDA topics covered in KubeAstronaut: ClusterTriggerAuthentication, ScaledJob with scaling strategies, KEDA with multiple sources, Service Mesh integration, and KEDA observability.

## Advanced Concepts

### ClusterTriggerAuthentication — Shared Credentials
While TriggerAuthentication is namespace-scoped, ClusterTriggerAuthentication is cluster-wide:

\`\`\`yaml
apiVersion: keda.sh/v1alpha1
kind: ClusterTriggerAuthentication
metadata:
  name: kafka-cluster-auth
  # No namespace — cluster-scoped!
spec:
  secretTargetRef:
    - parameter: sasl.user
      name: kafka-credentials
      namespace: keda  # namespace of the Secret
      key: username
    - parameter: sasl.password
      name: kafka-credentials
      namespace: keda
      key: password

---
# Reference from ScaledObject in any namespace
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: my-scaler
  namespace: team-a   # different namespace!
spec:
  scaleTargetRef:
    name: my-deployment
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka:9092
        topic: orders
        lagThreshold: "10"
      authenticationRef:
        name: kafka-cluster-auth
        kind: ClusterTriggerAuthentication  # REQUIRED!
\`\`\`

### ScaledJob — Advanced Scaling Strategies

#### Accurate Strategy
Creates exactly 1 Job per message/item:
\`\`\`yaml
spec:
  scalingStrategy:
    strategy: accurate
    # Formula: targetPendingJobs = queueLength - runningJobs
\`\`\`

#### Custom Strategy
Fine-grained control over how many jobs to create:
\`\`\`yaml
spec:
  scalingStrategy:
    strategy: custom
    customScalingQueueLengthDeduction: 1
    # Deduct X from queue per running job
    customScalingRunningJobPercentage: "0.5"
    # Consider 50% of running jobs still processing
    pendingJobCount: 100
    # Limit jobs in Pending state
\`\`\`

#### Rollout Strategy
\`\`\`yaml
spec:
  rollout:
    strategy: gradual   # gradual | default
    propagationPolicy: foreground
    # gradual: wait for previous jobs to complete before creating new ones
    # default: create jobs immediately
\`\`\`

### KEDA with KEDA HTTP Add-on
The HTTP Add-on enables scaling based on queued HTTP requests (scale-to-zero for APIs):

\`\`\`yaml
# Install HTTP Add-on
helm install http-add-on kedacore/keda-add-ons-http \\
  --namespace keda

---
# HTTPScaledObject (different from standard ScaledObject)
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  name: api-http-scaler
  namespace: default
spec:
  hosts:
    - api.example.com
  pathPrefixes:
    - /api/
  targetPendingRequests: 100   # queued requests per pod
  scaleTargetRef:
    deployment: api-deployment
    service: api-service
    port: 8080
  replicas:
    min: 0
    max: 30
\`\`\`

### KEDA Metrics API — Integrating with Standard HPA
\`\`\`yaml
# Using KEDA metrics in a standard HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: custom-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app
  minReplicas: 2
  maxReplicas: 50
  metrics:
    - type: External
      external:
        metric:
          name: s0-kafka-orders   # name generated by KEDA
          selector:
            matchLabels:
              scaledobject.keda.sh/name: my-scaler
        target:
          type: Value
          value: "10"
\`\`\`

### KEDA Observability

#### KEDA Metrics Exposed via Prometheus
\`\`\`bash
# Main keda-operator metrics
keda_scaler_active                # 1 if scaler active, 0 if not
keda_scaler_metrics_value         # current metric value
keda_scaler_errors_total          # polling errors
keda_scaled_object_errors_total   # errors per ScaledObject
keda_resource_totals              # total KEDA resources

# Verify via port-forward
kubectl port-forward -n keda svc/keda-operator-metrics-apiserver 8080:8080
curl http://localhost:8080/metrics | grep keda_scaler
\`\`\`

#### ServiceMonitor for kube-prometheus-stack
\`\`\`yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keda-operator
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: keda-operator
  namespaceSelector:
    matchNames:
      - keda
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
\`\`\`

### Pattern: KEDA with Argo Rollouts
Integration with progressive deployments:
\`\`\`yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rollout-scaler
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout          # points to Rollout instead of Deployment
    name: my-rollout
  minReplicaCount: 2
  maxReplicaCount: 50
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka:9092
        topic: events
        lagThreshold: "15"
\`\`\`

### Pattern: Fallback Configuration
Configure behavior when the external source is unavailable:
\`\`\`yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: resilient-scaler
spec:
  scaleTargetRef:
    name: my-deployment
  minReplicaCount: 2
  maxReplicaCount: 50
  fallback:
    failureThreshold: 3     # failures before activating fallback
    replicas: 5             # replicas during fallback
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka:9092
        topic: orders
        lagThreshold: "10"
\`\`\`

### Pattern: KEDA with VPA (Vertical Pod Autoscaler)
Use KEDA for horizontal scaling and VPA for vertical scaling:
\`\`\`yaml
# VPA to adjust pod resources
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: consumer-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kafka-consumer
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: consumer
        minAllowed:
          cpu: 100m
          memory: 128Mi
        maxAllowed:
          cpu: 2
          memory: 2Gi

# ScaledObject for horizontal scaling
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-consumer-scaler
spec:
  scaleTargetRef:
    name: kafka-consumer
  minReplicaCount: 1
  maxReplicaCount: 20
  triggers:
    - type: kafka
      metadata:
        lagThreshold: "50"
\`\`\`

### Scaling StatefulSets
\`\`\`yaml
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: statefulset-scaler
spec:
  scaleTargetRef:
    kind: StatefulSet
    name: redis-cluster
  minReplicaCount: 3    # minimum for quorum
  maxReplicaCount: 9
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 600  # 10min for StatefulSet
          policies:
            - type: Pods
              value: 1           # only 1 pod at a time (safe for StatefulSet)
              periodSeconds: 120
  triggers:
    - type: redis
      metadata:
        address: redis-cluster:6379
        listName: tasks
        listLength: "100"
\`\`\`

## Essential Commands

### Advanced Debug
\`\`\`bash
# View all available external metrics in the cluster
kubectl get --raw "/apis/external.metrics.k8s.io/v1beta1" | \\
  jq '.resources[].name'

# View current value of a specific metric
kubectl get --raw \\
  "/apis/external.metrics.k8s.io/v1beta1/namespaces/default/s0-kafka-orders" | \\
  jq '.items[0]'

# Verify admission webhook is responding
kubectl get validatingwebhookconfiguration | grep keda
kubectl get mutatingwebhookconfiguration | grep keda

# Check webhook certificate
kubectl get secret -n keda keda-operator-certs -o yaml | \\
  grep tls.crt | awk '{print \$2}' | base64 -d | \\
  openssl x509 -text -noout | grep "Not After"

# Force re-sync of a ScaledObject
kubectl patch scaledobject my-scaler --type merge \\
  -p '{"metadata":{"annotations":{"autoscaling.keda.sh/restartedAt":"'"\$(date -u +%Y-%m-%dT%H:%M:%SZ)"'"}}}'

# View ScaledJob details
kubectl describe scaledjob image-processor
kubectl get jobs -l scaledjob.keda.sh/name=image-processor
\`\`\`

### ClusterTriggerAuthentication Management
\`\`\`bash
# List CTAs
kubectl get clustertriggerauthentication

# Check which ScaledObjects use a CTA
kubectl get scaledobject --all-namespaces -o json | \\
  jq '.items[] | select(.spec.triggers[].authenticationRef.kind=="ClusterTriggerAuthentication") | .metadata'

# Update referenced Secret (rotated credentials)
kubectl create secret generic kafka-credentials \\
  -n keda \\
  --from-literal=username=new-user \\
  --from-literal=password=new-pass \\
  --dry-run=client -o yaml | kubectl apply -f -
# KEDA picks up automatically on next check
\`\`\`

## YAML Examples

### Complete Pipeline: Kafka → KEDA → ScaledJob → S3
\`\`\`yaml
# 1. Secret with credentials
apiVersion: v1
kind: Secret
metadata:
  name: pipeline-creds
  namespace: processing
stringData:
  kafka-username: processor
  kafka-password: "s3cr3t"
  aws-role-arn: "arn:aws:iam::123456789:role/s3-writer"

---
# 2. TriggerAuthentication
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: pipeline-auth
  namespace: processing
spec:
  secretTargetRef:
    - parameter: sasl.user
      name: pipeline-creds
      key: kafka-username
    - parameter: sasl.password
      name: pipeline-creds
      key: kafka-password

---
# 3. ScaledJob for processing
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: data-processor
  namespace: processing
spec:
  jobTargetRef:
    parallelism: 1
    completions: 1
    backoffLimit: 3
    activeDeadlineSeconds: 300
    template:
      metadata:
        labels:
          app: data-processor
      spec:
        serviceAccountName: s3-writer-sa  # IRSA for AWS
        restartPolicy: Never
        containers:
          - name: processor
            image: my-data-processor:v1.2.0
            env:
              - name: KAFKA_BOOTSTRAP
                value: kafka.kafka:9092
              - name: S3_BUCKET
                value: my-data-bucket
            resources:
              requests:
                memory: 256Mi
                cpu: 250m
              limits:
                memory: 512Mi
                cpu: 500m

  maxReplicaCount: 50
  pollingInterval: 10
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3

  scalingStrategy:
    strategy: accurate

  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka.kafka:9092
        consumerGroup: data-processors
        topic: raw-data
        lagThreshold: "1"
        activationLagThreshold: "0"
        sasl: plain
      authenticationRef:
        name: pipeline-auth

---
# 4. ServiceAccount with IRSA
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-writer-sa
  namespace: processing
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789:role/s3-writer
\`\`\`

## Common Mistakes

### 1. ClusterTriggerAuthentication referenced without specifying kind
**Problem**: ScaledObject can't find the authentication and fails.
**Cause**: authenticationRef without \`kind: ClusterTriggerAuthentication\`.
**Fix**: Always specify the kind when using CTA.
\`\`\`yaml
authenticationRef:
  name: my-cluster-auth
  kind: ClusterTriggerAuthentication  # REQUIRED
\`\`\`

### 2. ScaledJob accumulates completed/failed Jobs
**Cause**: successfulJobsHistoryLimit and failedJobsHistoryLimit not configured.
**Fix**: Define history limits in the ScaledJob.
\`\`\`yaml
spec:
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
\`\`\`

### 3. Admission webhook rejects ScaledObject
**Cause**: Webhook certificate expired or webhook not responding.
**Fix**: Upgrade or reinstall KEDA via Helm.

### 4. Fallback not activating correctly
**Cause**: failureThreshold too high — source is unavailable for insufficient time.
**Fix**: Lower threshold and verify source is actually unreachable.

### 5. StatefulSet scales too fast causing instability
**Cause**: Scale-down policies too aggressive for StatefulSets.
**Fix**: Use \`type: Pods\` with \`value: 1\` and high period for StatefulSets.

## Killer.sh Style Challenge

**Context**: A fintech company processes transactions via Kafka. Requirements:
1. The transaction processor must scale based on Kafka lag (group: \`txn-processors\`)
2. Kafka credentials must be shared across 3 namespaces (payments, fraud, analytics)
3. In case of Kafka failure, maintain 3 replicas (fallback)
4. Scale down at most 1 pod at a time (stability)
5. Maximum 100 pods, minimum 2

Create ClusterTriggerAuthentication + ScaledObject meeting all requirements.`,

  quiz: [
    {
      question: 'What is the difference between TriggerAuthentication and ClusterTriggerAuthentication?',
      options: [
        'TriggerAuthentication supports more providers; ClusterTriggerAuthentication is simpler',
        'TriggerAuthentication is namespace-scoped; ClusterTriggerAuthentication is accessible cluster-wide',
        'ClusterTriggerAuthentication only works with Kafka and RabbitMQ',
        'There is no practical difference — they are equivalent'
      ],
      correct: 1,
      explanation: 'TriggerAuthentication is namespace-scoped and can only be referenced by ScaledObjects in the same namespace. ClusterTriggerAuthentication is cluster-scoped and can be reused by ScaledObjects in any namespace — ideal for credentials shared across teams.',
      reference: 'CRD: ClusterTriggerAuthentication — dedicated section in theory.'
    },
    {
      question: 'Which ScaledObject field configures behavior when the metrics source becomes unavailable?',
      options: [
        'spec.errorPolicy',
        'spec.fallback',
        'spec.recovery',
        'spec.highAvailability'
      ],
      correct: 1,
      explanation: 'The spec.fallback field defines graceful degradation behavior: failureThreshold specifies how many consecutive failures activate the fallback, and replicas specifies how many replicas to maintain during degradation. Without fallback, KEDA uses the last known metric.',
      reference: 'Config: fallback — "Pattern: Fallback Configuration" section in theory.'
    },
    {
      question: 'When should you use the "accurate" strategy in ScaledJob?',
      options: [
        'When you need to process each message exactly once, creating 1 Job per message',
        'When you want to maximize throughput regardless of message count',
        'When the job has multiple containers that need coordination',
        'Only for machine learning workloads with large datasets'
      ],
      correct: 0,
      explanation: 'The "accurate" strategy creates exactly 1 Job per message/queue item, subtracting running jobs from the total. It\'s ideal for one-shot processing where each message must be handled by a dedicated job, like data transformation or email sending.',
      reference: 'ScaledJob: accurate strategy — "ScaledJob — Advanced Scaling Strategies" section in theory.'
    },
    {
      question: 'How do you reference a ClusterTriggerAuthentication in a ScaledObject?',
      options: [
        'authenticationRef: name: my-cta (no kind = uses CTA automatically)',
        'authenticationRef: name: my-cta kind: ClusterTriggerAuthentication',
        'clusterAuthenticationRef: name: my-cta',
        'authenticationRef: cluster: true name: my-cta'
      ],
      correct: 1,
      explanation: 'You MUST specify kind: ClusterTriggerAuthentication in the authenticationRef. Without the kind, KEDA looks for a namespace-scoped TriggerAuthentication and fails. The name + kind combination is the correct way to reference cluster-scoped resources.',
      reference: 'Common mistakes: CTA without kind — "Common Mistakes" section in theory.'
    },
    {
      question: 'For safely scaling a StatefulSet with KEDA, which scale-down policy is most appropriate?',
      options: [
        'type: Percent value: 50 — remove 50% of replicas per period',
        'type: Pods value: 1 with high period — only 1 pod at a time',
        'type: Pods value: 3 — remove up to 3 pods per period for agility',
        'No policies — let KEDA manage automatically'
      ],
      correct: 1,
      explanation: 'StatefulSets have ordering and identity guarantees that make aggressive scale-down dangerous (can break quorum in distributed databases). Using type: Pods value: 1 with a high period (120s+) ensures only 1 pod is removed at a time, allowing time for rebalancing.',
      reference: 'Pattern: StatefulSet — "Scaling StatefulSets" section in theory.'
    },
    {
      question: 'Which KEDA metric indicates whether a scaler is active (receiving events)?',
      options: [
        'keda_operator_active_scalers',
        'keda_scaler_active',
        'keda_scaled_object_replicas_current',
        'keda_trigger_active_total'
      ],
      correct: 1,
      explanation: 'keda_scaler_active is a gauge that returns 1 when the scaler is active (there are events/messages) and 0 when inactive (no load). It\'s useful for alerts and dashboards — allows detecting when workloads were scaled to zero and are awaiting events.',
      reference: 'Observability: KEDA metrics — "KEDA Observability" section in theory.'
    },
    {
      question: 'What is the KEDA HTTP Add-on and what use case does it solve?',
      options: [
        'A webhook for KEDA configuration via HTTP REST API',
        'A component that enables scale-to-zero for HTTP APIs based on pending requests',
        'An HTTP proxy for routing requests to the correct pod',
        'An extension for monitoring HTTP endpoints and creating alerts'
      ],
      correct: 1,
      explanation: 'The KEDA HTTP Add-on adds an interceptor proxy in front of APIs. With 0 replicas, the proxy buffers requests. When new requests arrive, KEDA scales from 0 to 1+ before forwarding. This enables true scale-to-zero for HTTP APIs without dropping requests.',
      reference: 'Component: KEDA HTTP Add-on — dedicated section in theory.'
    },
    {
      question: 'What is the effect of configuring successfulJobsHistoryLimit and failedJobsHistoryLimit in a ScaledJob?',
      options: [
        'Defines how many simultaneous jobs can exist at the same time',
        'Limits how many completed/failed Jobs are kept in history, preventing accumulation',
        'Defines the maximum number of retries per job before failing',
        'Controls log retention of jobs in Loki'
      ],
      correct: 1,
      explanation: 'Without these limits, completed and failed Jobs accumulate indefinitely in the cluster, consuming etcd resources and making kubectl get jobs unreadable. successfulJobsHistoryLimit keeps the last N successful jobs and failedJobsHistoryLimit keeps the last N failed ones.',
      reference: 'ScaledJob: history — "Complete Pipeline" YAML section in theory.'
    }
  ],

  flashcards: [
    {
      front: 'When to use ClusterTriggerAuthentication vs TriggerAuthentication?',
      back: 'TriggerAuthentication:\n- Namespace-scoped\n- Only used in the same namespace\n- For team-specific credentials\n- More secure (namespace isolation)\n\nClusterTriggerAuthentication:\n- Cluster-scoped\n- Reusable in any namespace\n- For shared credentials (central Kafka, shared RabbitMQ)\n- Requires kind: ClusterTriggerAuthentication in authenticationRef\n\nMandatory reference:\nauthenticationRef:\n  name: my-cta\n  kind: ClusterTriggerAuthentication'
    },
    {
      front: 'What does the ScaledObject fallback do?',
      back: 'Configures behavior when metrics source is unavailable:\n\nspec:\n  fallback:\n    failureThreshold: 3   # N consecutive failures\n    replicas: 5           # replicas during fallback\n\nFlow:\n1. Source becomes unavailable\n2. After failureThreshold failures → activates fallback\n3. Deployment maintained with N replicas\n4. When source recovers → returns to normal behavior\n\nWithout fallback: KEDA uses last known metric'
    },
    {
      front: 'What are the ScaledJob scaling strategies?',
      back: 'default:\n- Creates jobs proportionally to queue length\n- May create more jobs than messages\n\naccurate:\n- Exactly 1 job per message in lag\n- Formula: target = queueLen - runningJobs\n- More precise for one-shot processing\n\ncustom:\n- Fine control via customScalingQueueLengthDeduction\n- customScalingRunningJobPercentage\n- pendingJobCount (Pending jobs limit)'
    },
    {
      front: 'How to safely scale StatefulSets with KEDA?',
      back: 'Use HPA behavior with conservative policies:\n\nspec:\n  scaleTargetRef:\n    kind: StatefulSet\n    name: my-statefulset\n  minReplicaCount: 3  # minimum quorum\n  advanced:\n    horizontalPodAutoscalerConfig:\n      behavior:\n        scaleDown:\n          stabilizationWindowSeconds: 600\n          policies:\n            - type: Pods\n              value: 1    # 1 pod at a time\n              periodSeconds: 120'
    },
    {
      front: 'What are the main KEDA metrics for monitoring?',
      back: 'keda_scaler_active\n- 1 = scaler active (events exist), 0 = inactive\n\nkeda_scaler_metrics_value\n- Current value of the monitored metric\n\nkeda_scaler_errors_total\n- Source polling errors\n\nkeda_scaled_object_errors_total\n- Errors per ScaledObject\n\nkeda_resource_totals\n- Total KEDA resources in cluster\n\nAccess via:\nkubectl port-forward -n keda svc/keda-operator-metrics-apiserver 8080\ncurl http://localhost:8080/metrics'
    },
    {
      front: 'What is the KEDA HTTP Add-on and how does it work?',
      back: 'Enables scale-to-zero for HTTP APIs:\n\nArchitecture:\n1. Interceptor proxy sits in front of the API\n2. With 0 replicas: proxy buffers requests\n3. Requests arrive → KEDA scales from 0 to 1+\n4. Buffered requests are forwarded\n\nHTTPScaledObject:\n- targetPendingRequests: X (queued requests per pod)\n- hosts: domains to intercept\n- min/max replicas\n\nInstall:\nhelm install http-add-on kedacore/keda-add-ons-http'
    },
    {
      front: 'How to renew KEDA webhook certificates?',
      back: '# Check certificate validity\nkubectl get secret -n keda keda-operator-certs \\\n  -o jsonpath=\'{.data.tls\\.crt}\' | \\\n  base64 -d | openssl x509 -text | grep "Not After"\n\n# Renew via helm upgrade\nhelm upgrade keda kedacore/keda \\\n  -n keda --reuse-values\n\n# Or clean reinstall if needed\nhelm uninstall keda -n keda\nhelm install keda kedacore/keda -n keda\n\n# Verify webhook after renewal\nkubectl get validatingwebhookconfiguration | grep keda'
    },
    {
      front: 'How to force re-sync a ScaledObject without recreating it?',
      back: '# Add annotation to force re-sync\nkubectl patch scaledobject my-scaler --type merge \\\n  -p \'{"metadata":{"annotations":{"autoscaling.keda.sh/restartedAt":"2024-01-01T00:00:00Z"}}}\'\n\n# Or use current timestamp\nkubectl annotate scaledobject my-scaler \\\n  autoscaling.keda.sh/restartedAt="$(date -u +%Y-%m-%dT%H:%M:%SZ)" \\\n  --overwrite\n\nUseful when:\n- TriggerAuthentication was updated\n- External source recovered after downtime\n- Credentials rotated'
    }
  ],

  lab: {
    scenario: 'You are the Platform Engineer responsible for an event processing platform. Multiple teams (payments, analytics, fraud) consume from the same Kafka cluster and need automatic scaling. You must configure shared credentials and ScaledObjects for each team, with fallback and safe scale-down policies.',
    objective: 'Configure ClusterTriggerAuthentication, multiple ScaledObjects with fallback, ScaledJob for batch processing, and ServiceMonitor for KEDA observability.',
    duration: '40-50 minutes',
    steps: [
      {
        title: 'Configure ClusterTriggerAuthentication and Namespaces',
        instruction: `Create namespaces for the teams and configure shared credentials via ClusterTriggerAuthentication, simulating Kafka credentials shared across multiple teams.

Use Redis as a simulation of "event source" (since Kafka requires more infrastructure).`,
        hints: [
          'ClusterTriggerAuthentication has no namespace in its metadata',
          'The Secret referenced by CTA MUST be in a specific namespace — use keda or a dedicated namespace',
          'To test without real Kafka, use the Redis scaler which is simpler to set up'
        ],
        solution: `\`\`\`bash
# Create team namespaces
kubectl create namespace payments
kubectl create namespace analytics
kubectl create namespace fraud

# Create Secret with credentials (in dedicated namespace)
kubectl create namespace platform
kubectl create secret generic redis-credentials \\
  -n platform \\
  --from-literal=address="redis.default:6379"

# Create ClusterTriggerAuthentication
kubectl apply -f - <<EOF
apiVersion: keda.sh/v1alpha1
kind: ClusterTriggerAuthentication
metadata:
  name: redis-cluster-auth
  # NO namespace!
spec:
  secretTargetRef:
    - parameter: address
      name: redis-credentials
      namespace: platform
      key: address
EOF

# Verify CTA created
kubectl get clustertriggerauthentication
\`\`\``,
        verify: `\`\`\`bash
# Verify namespaces
kubectl get namespaces | grep -E "payments|analytics|fraud|platform"
# Expected: 4 namespaces created

# Verify Secret
kubectl get secret redis-credentials -n platform
# Expected: redis-credentials   Opaque   1   Xs

# Verify ClusterTriggerAuthentication
kubectl get clustertriggerauthentication redis-cluster-auth
# Expected: redis-cluster-auth   Xs

# Describe CTA
kubectl describe clustertriggerauthentication redis-cluster-auth
# Expected: SecretTargetRef with address mapped
\`\`\``
      },
      {
        title: 'Deploy Team Workers with ScaledObjects and Fallback',
        instruction: `Deploy one worker per namespace (payments, analytics) and configure ScaledObjects using the created ClusterTriggerAuthentication.

Also configure fallback to maintain minimum replicas if Redis becomes unavailable.

- payments-worker: list "payments-tasks", min=1, max=20, lagThreshold=3, fallback=2
- analytics-worker: list "analytics-tasks", min=0, max=10, lagThreshold=5, fallback=1`,
        hints: [
          'Each worker stays in its own namespace',
          'authenticationRef requires kind: ClusterTriggerAuthentication',
          'Redis is in the default namespace — use redis.default:6379',
          'To test fallback functionality, simulate unavailability later'
        ],
        solution: `\`\`\`bash
# Deploy payments worker
kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-worker
  namespace: payments
spec:
  replicas: 0
  selector:
    matchLabels:
      app: payments-worker
  template:
    metadata:
      labels:
        app: payments-worker
    spec:
      containers:
        - name: worker
          image: redis:7-alpine
          command: ["sh", "-c", "while true; do redis-cli -h redis.default RPOP payments-tasks; sleep 1; done"]
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: payments-scaler
  namespace: payments
spec:
  scaleTargetRef:
    name: payments-worker
  minReplicaCount: 1
  maxReplicaCount: 20
  cooldownPeriod: 60
  fallback:
    failureThreshold: 3
    replicas: 2
  triggers:
    - type: redis
      metadata:
        address: redis.default:6379
        listName: payments-tasks
        listLength: "3"
        activationListLength: "1"
      authenticationRef:
        name: redis-cluster-auth
        kind: ClusterTriggerAuthentication
EOF

# Deploy analytics worker
kubectl apply -f - <<EOF
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-worker
  namespace: analytics
spec:
  replicas: 0
  selector:
    matchLabels:
      app: analytics-worker
  template:
    metadata:
      labels:
        app: analytics-worker
    spec:
      containers:
        - name: worker
          image: redis:7-alpine
          command: ["sh", "-c", "while true; do redis-cli -h redis.default RPOP analytics-tasks; sleep 2; done"]
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: analytics-scaler
  namespace: analytics
spec:
  scaleTargetRef:
    name: analytics-worker
  minReplicaCount: 0
  maxReplicaCount: 10
  cooldownPeriod: 30
  fallback:
    failureThreshold: 3
    replicas: 1
  triggers:
    - type: redis
      metadata:
        address: redis.default:6379
        listName: analytics-tasks
        listLength: "5"
        activationListLength: "2"
      authenticationRef:
        name: redis-cluster-auth
        kind: ClusterTriggerAuthentication
EOF
\`\`\``,
        verify: `\`\`\`bash
# Verify ScaledObjects in both namespaces
kubectl get scaledobject -n payments
kubectl get scaledobject -n analytics
# Expected: READY = True for both

# Test scaling by inserting tasks
kubectl exec deployment/redis -- redis-cli LPUSH payments-tasks pay-{1..15}
kubectl exec deployment/redis -- redis-cli LPUSH analytics-tasks ana-{1..8}

sleep 15

kubectl get pods -n payments
# Expected: payments-worker pods scaled up (min 5)
kubectl get pods -n analytics
# Expected: analytics-worker pods scaled up

# Verify CTA is reused
kubectl get scaledobject -n payments payments-scaler -o yaml | \\
  grep -A3 "authenticationRef"
# Expected: kind: ClusterTriggerAuthentication
\`\`\``
      },
      {
        title: 'Configure ServiceMonitor and KEDA Observability',
        instruction: `Configure KEDA monitoring itself via Prometheus, creating a ServiceMonitor to collect metrics from the keda-operator.

Then verify scaling metrics and create a simple alert for KEDA errors.`,
        hints: [
          'KEDA exposes metrics on port 8080 of the metrics-apiserver',
          'ServiceMonitor needs to be in the kube-prometheus-stack namespace to be detected',
          'Use keda_scaler_active to verify scalers are active',
          'keda_scaler_errors_total indicates connectivity problems with sources'
        ],
        solution: `\`\`\`bash
# Verify Prometheus Operator is installed
kubectl get crd servicemonitors.monitoring.coreos.com

# Create ServiceMonitor for KEDA
kubectl apply -f - <<EOF
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keda-operator-metrics
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: keda-operator
  namespaceSelector:
    matchNames:
      - keda
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      scheme: http
EOF

# Verify metrics via port-forward
kubectl port-forward -n keda svc/keda-operator-metrics-apiserver 8080:8080 &

# View KEDA metrics
curl -s http://localhost:8080/metrics | grep -E "keda_scaler_active|keda_scaler_errors"

# Create alert for KEDA errors
kubectl apply -f - <<EOF
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: keda-alerts
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
spec:
  groups:
    - name: keda
      rules:
        - alert: KEDAScalerError
          expr: increase(keda_scaler_errors_total[5m]) > 0
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "KEDA scaler error for {{ \$labels.scaledobject }}"
            description: "Scaler {{ \$labels.scaler_type }} failing for {{ \$labels.scaledobject }}"
EOF
\`\`\``,
        verify: `\`\`\`bash
# Verify ServiceMonitor created
kubectl get servicemonitor -n monitoring keda-operator-metrics
# Expected: keda-operator-metrics   Xm

# Verify available metrics
curl -s http://localhost:8080/metrics | \\
  grep keda_scaler_active | head -5
# Expected: keda_scaler_active{...} 0 or 1

# Verify PrometheusRule
kubectl get prometheusrule -n monitoring keda-alerts
# Expected: keda-alerts   Xm

# View metrics per ScaledObject
curl -s http://localhost:8080/metrics | \\
  grep keda_scaler_metrics_value
# Expected: numeric values per scaler

# Test alert by checking errors (should be 0 if all OK)
curl -s http://localhost:8080/metrics | \\
  grep keda_scaler_errors_total
# Expected: keda_scaler_errors_total{...} 0
\`\`\``
      }
    ]
  },

  troubleshooting: [
    {
      title: 'authenticationRef with ClusterTriggerAuthentication returns "not found"',
      difficulty: 'easy',
      symptom: 'ScaledObject with ClusterTriggerAuthentication reference is READY: False. keda-operator logs show "TriggerAuthentication not found".',
      diagnosis: `\`\`\`bash
# Check if CTA exists
kubectl get clustertriggerauthentication

# View the ScaledObject authenticationRef
kubectl get scaledobject my-scaler -o yaml | \\
  grep -A5 "authenticationRef"

# Check operator logs
kubectl logs -n keda -l app=keda-operator --tail=30 | \\
  grep -i "authentication\\|trigger auth"

# Verify referenced Secret exists
kubectl get secret -n platform my-credentials

# Check if Secret namespace matches CTA config
kubectl get clustertriggerauthentication my-cta -o yaml | \\
  grep -A5 "secretTargetRef"
\`\`\``,
      solution: `**Most common cause**: \`authenticationRef\` missing \`kind: ClusterTriggerAuthentication\`.

\`\`\`bash
# Check current ScaledObject
kubectl get scaledobject my-scaler -o yaml | grep -A5 authenticationRef

# If kind is missing, edit:
kubectl edit scaledobject my-scaler
# Fix to:
# authenticationRef:
#   name: my-cluster-auth
#   kind: ClusterTriggerAuthentication  ← ADD THIS
\`\`\`

**Cause 2**: Referenced Secret doesn't exist in specified namespace.
\`\`\`bash
# Check Secret in CTA
kubectl get clustertriggerauthentication my-cta -o yaml

# Create Secret in correct namespace (e.g. platform)
kubectl create secret generic my-credentials \\
  -n platform \\
  --from-literal=username=user \\
  --from-literal=password=pass
\`\`\`

**Cause 3**: CTA exists but in wrong namespace.
\`\`\`bash
# CTA should NOT have a namespace
kubectl get clustertriggerauthentication -A
# If appearing in a specific namespace, it's a TriggerAuthentication (namespace-scoped)
# Recreate as ClusterTriggerAuthentication without namespace
\`\`\``
    },
    {
      title: 'ScaledJob accumulates hundreds of completed Jobs',
      difficulty: 'medium',
      symptom: 'kubectl get jobs shows hundreds of Jobs with Completed or Failed status. The namespace consumes excessive etcd space and kubectl queries are slow.',
      diagnosis: `\`\`\`bash
# Count accumulated jobs
kubectl get jobs -n processing | wc -l

# View status distribution
kubectl get jobs -n processing -o json | \\
  jq '.items[] | .status.conditions[0].type' | sort | uniq -c

# Check ScaledJob configuration
kubectl get scaledjob data-processor -n processing -o yaml | \\
  grep -E "historyLimit|successfulJobs|failedJobs"

# Check etcd usage (if accessible)
kubectl get --raw /healthz/etcd

# Check oldest jobs age
kubectl get jobs -n processing --sort-by=.metadata.creationTimestamp | head -5
\`\`\``,
      solution: `**Immediate solution — Clean up accumulated jobs**:
\`\`\`bash
# Delete completed jobs
kubectl delete jobs -n processing \\
  \$(kubectl get jobs -n processing \\
    -o go-template='{{range .items}}{{if .status.completionTime}}{{.metadata.name}} {{end}}{{end}}')

# Or using status field
kubectl get jobs -n processing -o json | \\
  jq -r '.items[] | select(.status.conditions[0].type=="Complete") | .metadata.name' | \\
  xargs kubectl delete job -n processing
\`\`\`

**Permanent fix — Configure limits in ScaledJob**:
\`\`\`bash
kubectl edit scaledjob data-processor -n processing
# Add/fix:
# spec:
#   successfulJobsHistoryLimit: 5   # keep only last 5 successful
#   failedJobsHistoryLimit: 3       # keep only last 3 failed
\`\`\`

**Prevention — Template with automatic TTL**:
\`\`\`yaml
spec:
  jobTargetRef:
    template:
      spec:
        # Automatic TTL cleanup (K8s 1.21+)
        ttlSecondsAfterFinished: 3600  # 1 hour after completion
\`\`\``
    }
  ]
};
