#!/usr/bin/env python3
"""Generate content/search-index.js — a lightweight full-text index for the search box.

For every topic it extracts the theory prose (PT + EN), strips fenced code blocks and
markdown noise, collapses whitespace, and stores a single searchable string. The result
is written as a JS global (loaded via <script>, so it works on file:// and HTTP):

    window.K8S_SEARCH_INDEX = { "domain/topic": "stripped prose ...", ... };

The search box (js/search.js) injects this file lazily on first use and uses it to match
against the body text and render a snippet. Regenerate whenever theory content changes:

    python scripts/build_search_index.py

PowerShell/Python only — never Node.
"""
import re, glob, json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content"
OUT = CONTENT / "search-index.js"
BACKTICK = "`"
BS = chr(92)

# per-topic prose cap (chars per language) to keep the index lean
CAP = 2400


def extract_theory(src):
    """Return the raw theory template string body, or '' if none."""
    m = re.search(r"theory:\s*`", src)
    if not m:
        return ""
    start = m.end()
    i = start
    while i < len(src):
        if src[i] == BS:
            i += 2
            continue
        if src[i] == BACKTICK:
            break
        i += 1
    return src[start:i]


def strip_markdown(text):
    """Remove code fences / markdown syntax, collapse whitespace."""
    # fenced code blocks ```...```
    text = re.sub(r"```.*?```", " ", text, flags=re.S)
    # inline code `...`
    text = re.sub(r"`[^`]*`", " ", text)
    # markdown tables (lines with pipes) — keep words, drop pipes/dashes
    text = text.replace("|", " ")
    # headings / list / emphasis markers
    text = re.sub(r"[#>*_~\-]+", " ", text)
    # links [text](url) -> text
    text = re.sub(r"\[([^\]]*)\]\([^)]*\)", r"\1", text)
    # escaped template chars
    text = text.replace(BS + "`", " ").replace(BS + "$", "$").replace(BS + BS, " ")
    # collapse whitespace
    text = re.sub(r"\s+", " ", text).strip()
    return text


def topic_text(path):
    parts = []
    for fname in ("topic.js", "topic-en.js"):
        f = CONTENT / path / fname
        if not f.exists():
            continue
        prose = strip_markdown(extract_theory(f.read_text(encoding="utf-8")))
        if prose:
            parts.append(prose[:CAP])
    return " ¦ ".join(parts)


def main():
    # registry declaration order
    reg = (CONTENT / "registry.js").read_text(encoding="utf-8")
    paths = []
    seen = set()
    for p in re.findall(r"path:\s*'([^']+)'", reg):
        if p not in seen:
            paths.append(p)
            seen.add(p)

    index = {}
    for p in paths:
        t = topic_text(p)
        if t:
            index[p] = t

    payload = json.dumps(index, ensure_ascii=False, separators=(",", ":"))
    OUT.write_text(
        "// AUTO-GENERATED by scripts/build_search_index.py — do not edit by hand.\n"
        "// Regenerate after changing theory content: python scripts/build_search_index.py\n"
        "window.K8S_SEARCH_INDEX = " + payload + ";\n",
        encoding="utf-8",
    )
    size = OUT.stat().st_size
    print("Wrote %s" % OUT.relative_to(ROOT).as_posix())
    print("  topics indexed: %d" % len(index))
    print("  file size: %.2f MB (%d bytes)" % (size / 1048576, size))


if __name__ == "__main__":
    main()
