window.K8S_CONTENT_EN = window.K8S_CONTENT_EN || {};
window.K8S_CONTENT_EN['istio-advanced/istio-observability'] = {
  theory: `
# Observability & Telemetry in Istio

## Relevance
Istio provides automatic observability without modifying application code. Metrics, distributed tracing, and access logs are generated by the Envoy sidecar. Integrations with Kiali, Jaeger, Prometheus, and Grafana provide complete mesh visibility. The Telemetry API enables declarative telemetry configuration.

## Core Concepts

### Automatic Metrics

Envoy generates standard metrics for each request:

| Metric | Description | Labels |
|--------|-------------|--------|
| istio_requests_total | Total requests | source, destination, response_code |
| istio_request_duration_milliseconds | Latency | source, destination |
| istio_request_bytes | Request size | source, destination |
| istio_response_bytes | Response size | source, destination |
| istio_tcp_connections_opened_total | TCP connections opened | source, destination |
| istio_tcp_connections_closed_total | TCP connections closed | source, destination |

**Prometheus scraping:**
\`\`\`yaml
# Envoy exposes metrics on port 15090
# istiod exposes metrics on port 15014
# Automatic Prometheus scraping via annotations
annotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "15090"
  prometheus.io/path: "/stats/prometheus"
\`\`\`

### Distributed Tracing with Jaeger

Istio automatically propagates tracing headers between sidecars:

\`\`\`
Propagated headers:
- x-request-id
- x-b3-traceid
- x-b3-spanid
- x-b3-parentspanid
- x-b3-sampled
- x-b3-flags
- traceparent (W3C)
- tracestate (W3C)
\`\`\`

**Important:** The application MUST propagate these headers between requests. Istio injects/extracts automatically at the sidecars, but if the app makes downstream calls, it needs to copy the headers.

**Configure tracing:**
\`\`\`yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      tracing:
        sampling: 100.0      # 100% = all requests (dev)
        zipkin:
          address: jaeger-collector.istio-system:9411
\`\`\`

### Kiali — Service Mesh Dashboard

Kiali is the official Istio dashboard that provides:

- **Graph visualization** — real-time mesh topology
- **Health monitoring** — service health status
- **Configuration validation** — detects errors in VirtualService, DestinationRule
- **Traffic analysis** — success rate, latency, throughput
- **Tracing integration** — links to spans in Jaeger

\`\`\`bash
# Install Kiali (included in demo profile)
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.20/samples/addons/kiali.yaml

# Access dashboard
istioctl dashboard kiali
\`\`\`

### Telemetry API

The Telemetry API enables declarative configuration of metrics, tracing, and access logs:

\`\`\`yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: namespace-telemetry
  namespace: production
spec:
  # Custom metrics
  metrics:
    - providers:
        - name: prometheus
      overrides:
        - match:
            metric: REQUEST_COUNT
            mode: CLIENT_AND_SERVER
          tagOverrides:
            request_host:
              value: "request.host"
  # Tracing
  tracing:
    - providers:
        - name: zipkin
      randomSamplingPercentage: 10.0
      customTags:
        environment:
          literal:
            value: "production"
  # Access Logging
  accessLogging:
    - providers:
        - name: envoy
      filter:
        expression: "response.code >= 400"
\`\`\`

### Access Logging

Configure access log format and filtering:

\`\`\`yaml
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: access-log
  namespace: istio-system       # mesh-wide
spec:
  accessLogging:
    - providers:
        - name: envoy
\`\`\`

\`\`\`yaml
# Custom format via MeshConfig
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
    accessLogFormat: |
      {
        "timestamp": "%START_TIME%",
        "method": "%REQ(:METHOD)%",
        "path": "%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%",
        "protocol": "%PROTOCOL%",
        "response_code": "%RESPONSE_CODE%",
        "response_flags": "%RESPONSE_FLAGS%",
        "upstream_host": "%UPSTREAM_HOST%",
        "duration": "%DURATION%"
      }
\`\`\`

### Common Mistakes

1. **Incomplete tracing** — the app does not propagate tracing headers between downstream calls
2. **100% sampling in production** — causes significant overhead; use 1-10%
3. **Access logs not appearing** — check Telemetry API and accessLogFile in MeshConfig
4. **Missing metrics** — sidecar not injected or stats filter was removed

## Killer.sh Style Challenge

> **Scenario:** Configure complete observability for the production namespace: (1) tracing at 10% with custom tag "env=production", (2) JSON access logs only for errors (status >= 400), (3) standard Prometheus metrics with custom label for request_host.
`,
  quiz: [
    {
      question: 'Which metrics does the Envoy sidecar generate automatically?',
      options: [
        'Only latency',
        'istio_requests_total, istio_request_duration_milliseconds, istio_request_bytes, istio_response_bytes',
        'Pod CPU and memory metrics',
        'Only request counts'
      ],
      correct: 1,
      explanation: 'Envoy automatically generates standard metrics: total requests, latency, request/response size, and TCP connections. All include labels like source, destination, and response_code.',
      reference: 'Related concept: Metrics are exposed on sidecar port 15090 for Prometheus scraping.'
    },
    {
      question: 'What is the application\'s responsibility in Istio distributed tracing?',
      options: [
        'Nothing, Istio does everything automatically',
        'The application must propagate tracing headers (x-b3-*, traceparent) between downstream calls',
        'The application must generate spans manually',
        'The application must send metrics to Jaeger'
      ],
      correct: 1,
      explanation: 'Although Istio injects tracing headers automatically at the sidecar, the application must propagate these headers when making calls to other services. Without this, traces become fragmented.',
      reference: 'Related concept: B3 (Zipkin) and W3C (traceparent/tracestate) headers are both supported.'
    },
    {
      question: 'What does Kiali provide that Prometheus and Grafana do not natively offer?',
      options: [
        'Latency metrics',
        'Mesh topology visualization and Istio configuration validation',
        'Automatic alerts',
        'Metrics storage'
      ],
      correct: 1,
      explanation: 'Kiali is the official Istio dashboard that shows the mesh service graph, health status, Istio CRD validation (errors in VirtualService, etc.), and tracing integration.',
      reference: 'Related concept: Kiali is installed as an addon — kubectl apply -f samples/addons/kiali.yaml.'
    },
    {
      question: 'How do you configure access logs for error requests only in Istio?',
      options: [
        'Edit the Envoy ConfigMap',
        'Use Telemetry API with filter expression "response.code >= 400"',
        'Configure log level in istiod',
        'Not possible to filter access logs'
      ],
      correct: 1,
      explanation: 'The Telemetry API allows declarative filters for access logs. The expression "response.code >= 400" captures only error responses, reducing log volume.',
      reference: 'Related concept: accessLogEncoding can be TEXT or JSON, configurable in MeshConfig.'
    },
    {
      question: 'What is the recommended tracing sampling rate for production?',
      options: [
        '100% to capture all traces',
        '1-10% to balance visibility and overhead',
        '0% to disable completely',
        '50% as default value'
      ],
      correct: 1,
      explanation: 'In production, 100% sampling causes significant processing and storage overhead. The recommendation is 1-10%, which provides sufficient visibility without impacting performance.',
      reference: 'Related concept: randomSamplingPercentage in Telemetry API or meshConfig.defaultConfig.tracing.sampling.'
    },
    {
      question: 'On which port does the Envoy sidecar expose metrics for Prometheus?',
      options: [
        '9090',
        '15090',
        '8080',
        '3000'
      ],
      correct: 1,
      explanation: 'The Envoy sidecar exposes Prometheus metrics on port 15090 at path /stats/prometheus. istiod exposes its metrics on port 15014.',
      reference: 'Related concept: Prometheus scrape annotations are added automatically by the sidecar injector.'
    },
    {
      question: 'Which declarative Istio API configures metrics, tracing, and access logs?',
      options: [
        'EnvoyFilter',
        'Telemetry API (telemetry.istio.io/v1alpha1)',
        'MeshConfig only',
        'DestinationRule'
      ],
      correct: 1,
      explanation: 'The Telemetry API (kind: Telemetry) is the declarative and recommended way to configure metrics, tracing, and access logs. It supports mesh-wide, namespace, or workload-level configuration.',
      reference: 'Related concept: Telemetry API replaces MeshConfig and EnvoyFilter configurations for telemetry.'
    }
  ],
  flashcards: [
    {
      front: 'What are the standard metrics generated by the Envoy sidecar?',
      back: '| Metric | Description |\n|--------|-------------|\n| **istio_requests_total** | Total requests |\n| **istio_request_duration_milliseconds** | Latency (histogram) |\n| **istio_request_bytes** | Request size |\n| **istio_response_bytes** | Response size |\n| **istio_tcp_connections_opened_total** | TCP connections opened |\n| **istio_tcp_connections_closed_total** | TCP connections closed |\n\n**Common labels:** source_workload, destination_service, response_code, request_protocol'
    },
    {
      front: 'How does distributed tracing work in Istio?',
      back: '1. Source sidecar **injects** tracing headers\n2. Application **propagates** headers to downstream calls\n3. Destination sidecar **extracts** headers\n4. Spans are sent to the collector (Jaeger/Zipkin)\n\n**Headers:** x-b3-traceid, x-b3-spanid, traceparent (W3C)\n\n**IMPORTANT:** The app MUST propagate headers — Istio only injects/extracts at sidecars.\n\n**Sampling:** 1-10% in prod, 100% in dev'
    },
    {
      front: 'What does Kiali offer as the Istio dashboard?',
      back: '**Visualization:**\n- Real-time service graph\n- Traffic flow between services\n- Success/error rate per service\n\n**Validation:**\n- Detects errors in VirtualService, DestinationRule\n- Verifies mesh configuration\n\n**Integration:**\n- Links to traces in Jaeger\n- Prometheus/Grafana metrics\n\n**Installation:**\nkubectl apply -f samples/addons/kiali.yaml\nistioctl dashboard kiali'
    },
    {
      front: 'How to configure the Telemetry API?',
      back: '**Scope:** mesh (istio-system), namespace, workload\n\n**Three pillars:**\n\n1. **Metrics:**\n\`\`\`yaml\nmetrics:\n  - providers: [{name: prometheus}]\n    overrides: [{tagOverrides: ...}]\n\`\`\`\n\n2. **Tracing:**\n\`\`\`yaml\ntracing:\n  - providers: [{name: zipkin}]\n    randomSamplingPercentage: 10\n    customTags: ...\n\`\`\`\n\n3. **Access Logging:**\n\`\`\`yaml\naccessLogging:\n  - providers: [{name: envoy}]\n    filter: {expression: "..."}\n\`\`\`'
    },
    {
      front: 'What is the difference between MeshConfig and Telemetry API for telemetry?',
      back: '**MeshConfig:**\n- Global configuration via IstioOperator\n- accessLogFile, accessLogFormat\n- tracing.sampling\n- Less flexible, mesh-wide only\n\n**Telemetry API:**\n- Declarative CRD (kind: Telemetry)\n- Granularity: mesh/namespace/workload\n- Filters with CEL expressions\n- Custom tags\n- Recommended API (newer)\n\n**Prefer** Telemetry API for new configurations.'
    },
    {
      front: 'What telemetry ports are important in Istio?',
      back: '| Port | Component | Function |\n|------|-----------|----------|\n| **15090** | Envoy sidecar | Prometheus metrics |\n| **15014** | istiod | Control plane metrics |\n| **15020** | Envoy sidecar | Health check / merged metrics |\n| **9411** | Jaeger collector | Receives spans (Zipkin format) |\n| **16685** | Jaeger query | Query API |\n| **20001** | Kiali | Web dashboard |\n| **3000** | Grafana | Dashboards |'
    },
    {
      front: 'How to debug fragmented traces in Jaeger?',
      back: '**Cause:** The application does not propagate tracing headers.\n\n**Verification:**\n1. Check if B3 or W3C headers reach the service\n2. Check if the app copies headers when making downstream calls\n\n**Solution:**\n- Propagate headers: x-request-id, x-b3-traceid, x-b3-spanid, traceparent\n- Use tracing SDK (OpenTelemetry) for automatic propagation\n- Check sampling rate > 0%\n\n**Tip:** In REST frameworks, use middleware/interceptor that copies headers automatically.'
    }
  ],
  lab: {
    scenario: 'You need to configure complete observability for the mesh: metrics in Prometheus, tracing in Jaeger, and filtered access logs.',
    objective: 'Install observability addons, configure Telemetry API, and verify metrics, traces, and logs.',
    duration: '20-25 minutes',
    steps: [
      {
        title: 'Install Observability Addons',
        instruction: `Install Prometheus, Grafana, Jaeger, and Kiali as Istio addons.

\`\`\`bash
# Install addons (assuming Istio is already installed)
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.20/samples/addons/prometheus.yaml
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.20/samples/addons/grafana.yaml
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.20/samples/addons/jaeger.yaml
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.20/samples/addons/kiali.yaml

# Wait for Pods to be ready
kubectl rollout status deployment prometheus -n istio-system
kubectl rollout status deployment grafana -n istio-system
kubectl rollout status deployment jaeger -n istio-system
kubectl rollout status deployment kiali -n istio-system

# Generate traffic to populate metrics
for i in \$(seq 1 100); do
  kubectl exec deploy/sleep -c sleep -- curl -s -o /dev/null http://productpage:9080/productpage
done
\`\`\``,
        hints: [
          'Addons are optional — Istio works without them',
          'In production, use dedicated Prometheus and Grafana installations',
          'The demo profile already includes tracing enabled with 100% sampling'
        ],
        solution: `\`\`\`bash
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.20/samples/addons/prometheus.yaml
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.20/samples/addons/grafana.yaml
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.20/samples/addons/jaeger.yaml
kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.20/samples/addons/kiali.yaml
\`\`\``,
        verify: `\`\`\`bash
# Verify addon Pods
kubectl get pods -n istio-system -l app=prometheus
kubectl get pods -n istio-system -l app=grafana
kubectl get pods -n istio-system -l app=jaeger
kubectl get pods -n istio-system -l app=kiali
# Expected output: all with STATUS Running

# Verify metrics in Prometheus
kubectl exec -n istio-system deploy/prometheus -- wget -qO- 'http://localhost:9090/api/v1/query?query=istio_requests_total' | head -5
# Expected output: results with Istio metrics
\`\`\``
      },
      {
        title: 'Configure Telemetry API',
        instruction: `Configure tracing with 10% sampling, access logs for errors only, and custom tags.

\`\`\`bash
kubectl apply -f - <<EOF
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: production-telemetry
  namespace: default
spec:
  # Tracing with 10% sampling and custom tags
  tracing:
    - providers:
        - name: zipkin
      randomSamplingPercentage: 10.0
      customTags:
        environment:
          literal:
            value: "staging"
        cluster_name:
          literal:
            value: "cluster-1"
  # Access logs for errors only
  accessLogging:
    - providers:
        - name: envoy
      filter:
        expression: "response.code >= 400"
  # Metrics with custom label
  metrics:
    - providers:
        - name: prometheus
      overrides:
        - match:
            metric: REQUEST_COUNT
            mode: CLIENT_AND_SERVER
          tagOverrides:
            request_host:
              value: "request.host"
EOF
\`\`\``,
        hints: [
          'Telemetry API supports mesh (istio-system), namespace, or workload scope',
          'randomSamplingPercentage: 10 = 10% of traces are captured',
          'filter.expression uses CEL (Common Expression Language)',
          'Custom tags are added to all spans'
        ],
        solution: `\`\`\`bash
kubectl apply -f telemetry-config.yaml
\`\`\``,
        verify: `\`\`\`bash
# Verify Telemetry
kubectl get telemetry production-telemetry
# Expected output: production-telemetry   Xs

# Verify applied configuration
kubectl get telemetry production-telemetry -o yaml | grep -A5 "tracing"
# Expected output: randomSamplingPercentage: 10

# Generate error traffic to test access logs
kubectl exec deploy/sleep -c sleep -- curl -s -o /dev/null -w "%{http_code}" http://productpage:9080/nonexistent
# Expected output: 404

# Verify access logs in sidecar (errors only)
kubectl logs deploy/productpage-v1 -c istio-proxy --tail=5 | grep "404"
# Expected output: log entry with response_code 404
\`\`\``
      },
      {
        title: 'Verify Tracing and Metrics',
        instruction: `Generate traffic and verify that traces and metrics are correctly collected.

\`\`\`bash
# Generate varied traffic
for i in \$(seq 1 50); do
  kubectl exec deploy/sleep -c sleep -- curl -s -o /dev/null http://productpage:9080/productpage
  kubectl exec deploy/sleep -c sleep -- curl -s -o /dev/null http://productpage:9080/nonexistent
done

# Verify metrics in Prometheus
kubectl exec -n istio-system deploy/prometheus -- wget -qO- \\
  'http://localhost:9090/api/v1/query?query=sum(istio_requests_total)%20by%20(destination_service_name,response_code)' 2>/dev/null

# Access dashboards (in separate terminal)
# istioctl dashboard kiali
# istioctl dashboard jaeger
# istioctl dashboard grafana

# Verify traces in Jaeger
kubectl exec -n istio-system deploy/jaeger -- wget -qO- \\
  'http://localhost:16686/api/traces?service=productpage.default&limit=5' 2>/dev/null | head -20
\`\`\``,
        hints: [
          'With 10% sampling, only ~10% of traces will be captured',
          'Metrics are always 100% (independent of tracing sampling)',
          'Use istioctl dashboard to access UIs locally',
          'Filtered access logs only show requests with status >= 400'
        ],
        solution: `\`\`\`bash
# Generate traffic
for i in \$(seq 1 50); do
  kubectl exec deploy/sleep -c sleep -- curl -s -o /dev/null http://productpage:9080/productpage
done

# Verify metrics
kubectl exec -n istio-system deploy/prometheus -- wget -qO- 'http://localhost:9090/api/v1/query?query=istio_requests_total'
\`\`\``,
        verify: `\`\`\`bash
# Verify Istio metrics exist in Prometheus
kubectl exec -n istio-system deploy/prometheus -- wget -qO- 'http://localhost:9090/api/v1/label/__name__/values' 2>/dev/null | grep istio_requests
# Expected output: "istio_requests_total" in the list

# Verify Kiali is accessible
kubectl get svc kiali -n istio-system
# Expected output: kiali   ClusterIP   ...   20001/TCP

# Verify Jaeger is accessible
kubectl get svc tracing -n istio-system
# Expected output: tracing   ClusterIP   ...   80/TCP,16685/TCP

# Verify applied Telemetry
kubectl get telemetry --all-namespaces
# Expected output: production-telemetry in default namespace
\`\`\``
      }
    ]
  },
  troubleshooting: [
    {
      title: 'Istio metrics not appearing in Prometheus',
      difficulty: 'easy',
      symptom: 'Prometheus is running but istio_requests_total and other Istio metrics are not showing up.',
      diagnosis: `\`\`\`bash
# Check if sidecar is present
kubectl get pods -o jsonpath='{range .items[*]}{.metadata.name}{" containers="}{range .spec.containers[*]}{.name}{","}{end}{"\\n"}{end}'

# Check if metrics are exposed by the sidecar
kubectl exec <pod> -c istio-proxy -- curl -s localhost:15090/stats/prometheus | grep istio_requests

# Check Prometheus targets
kubectl exec -n istio-system deploy/prometheus -- wget -qO- 'http://localhost:9090/api/v1/targets' 2>/dev/null | grep "istio-proxy"

# Check Prometheus scrape config
kubectl get configmap prometheus -n istio-system -o yaml | grep istio
\`\`\``,
      solution: `**Common causes:**

1. **Sidecar not injected:** Without the Envoy sidecar, there are no Istio metrics. Check injection label on the namespace.

2. **Prometheus not scraping:** Verify that Prometheus has the scrape job for istio-proxy configured.

3. **Stats filter removed:** If an EnvoyFilter removed the stats filter, metrics are not generated.

4. **Firewall/NetworkPolicy:** Verify that Prometheus can access port 15090 on the Pods.`
    },
    {
      title: 'Fragmented traces in Jaeger',
      difficulty: 'medium',
      symptom: 'Traces in Jaeger show individual spans but do not form a complete chain. Each service appears as a separate trace.',
      diagnosis: `\`\`\`bash
# Check tracing headers in proxy
kubectl logs <pod> -c istio-proxy | grep -i "x-b3\\|traceparent"

# Check sampling rate
kubectl get configmap istio -n istio-system -o jsonpath='{.data.mesh}' | grep sampling

# Check Telemetry
kubectl get telemetry --all-namespaces -o yaml | grep -A5 tracing

# Check if app propagates headers (test manually)
kubectl exec <pod> -c <app-container> -- curl -v http://<downstream-service> -H "x-b3-traceid: test123"
\`\`\``,
      solution: `**Causes and solutions:**

1. **App does not propagate headers:** The most common cause. The application must copy x-b3-* or traceparent headers when making downstream calls.

Solution: Add middleware that propagates headers automatically. In many frameworks, this is an HTTP interceptor.

2. **Inconsistent sampling:** If different services have different sampling rates, traces may be incomplete. Standardize via Telemetry API at namespace level.

3. **Unreachable collector:** If the Jaeger collector is not reachable, spans are discarded. Check Service and endpoints.

4. **Incompatible tracing format:** Ensure all services use the same format (B3 or W3C).`
    },
    {
      title: 'Access logs not appearing despite Telemetry configuration',
      difficulty: 'medium',
      symptom: 'Configured Telemetry API with accessLogging but logs are not showing in the istio-proxy container stdout.',
      diagnosis: `\`\`\`bash
# Check Telemetry resource
kubectl get telemetry --all-namespaces -o yaml

# Check MeshConfig
kubectl get configmap istio -n istio-system -o jsonpath='{.data.mesh}' | grep accessLog

# Check proxy logs
kubectl logs <pod> -c istio-proxy --tail=20

# Check if traffic is flowing
kubectl exec <pod> -c istio-proxy -- curl -s localhost:15000/stats | grep downstream_rq

# Check applied configuration in proxy
istioctl proxy-config log <pod> --level debug
\`\`\``,
      solution: `**Causes and solutions:**

1. **Wrong provider:** The provider must be "envoy" for logs in the istio-proxy stdout.

2. **Too restrictive filter:** If the expression filters by response.code >= 500, 4xx errors will not appear. Adjust the filter.

3. **Wrong scope:** The Telemetry must be in the correct namespace or in istio-system for mesh-wide.

4. **MeshConfig overriding:** If accessLogFile is empty in MeshConfig, it may disable logs globally. Check with:
\`\`\`bash
kubectl get cm istio -n istio-system -o jsonpath='{.data.mesh}' | grep accessLog
\`\`\`

5. **Proxy not updated:** After applying Telemetry, it may be necessary to wait or restart Pods for the proxy to reload the configuration.`
    }
  ]
};
