window.K8S_CONTENT_EN = window.K8S_CONTENT_EN || {};
window.K8S_CONTENT_EN['prom-fundamentals/promql-advanced'] = {
  theory: `
# Advanced PromQL

## Relevance
After mastering PromQL fundamentals, the next step is learning advanced techniques like vector matching, subqueries, histogram functions, and recording rules. These concepts are essential for complex dashboards, precise alerts, and Prometheus performance optimization.

## Core Concepts

### Vector Matching — Operations Between Metrics

When you perform binary operations between two vectors (e.g., A / B), Prometheus needs to know how to pair the time series. This is done through **vector matching**.

#### One-to-One Matching
By default, Prometheus pairs series that have **exactly the same labels**:
\`\`\`promql
# Works if both have the same labels
http_requests_total{method="GET"} / http_responses_total{method="GET"}
\`\`\`

#### Using on() and ignoring()
\`\`\`promql
# Match only by the "method" label (ignore others)
http_requests_total / on(method) http_responses_total

# Match ignoring the "instance" label
http_requests_total / ignoring(instance) http_responses_total
\`\`\`

#### Many-to-One and One-to-Many (group_left / group_right)
When one side has more series than the other:
\`\`\`promql
# Many request series, one capacity series per job
rate(http_requests_total[5m]) / on(job) group_left http_capacity

# group_left: the LEFT side has more series (many-to-one)
# group_right: the RIGHT side has more series (one-to-many)
\`\`\`

\`\`\`promql
# Practical example: add node info to pods
container_memory_usage_bytes
  * on(node) group_left(role)
  kube_node_labels{label_role="worker"}
\`\`\`

### Subqueries

Subqueries allow you to apply instant vector functions over dynamically created range vectors:

\`\`\`promql
# Syntax: <instant_query>[<range>:<resolution>]

# Average request rate over the last 30 minutes, calculated every 5 minutes
avg_over_time(rate(http_requests_total[5m])[30m:5m])

# Maximum CPU over the last 60 minutes, 1-minute resolution
max_over_time(
  (1 - avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])))[60m:1m]
)
\`\`\`

> **Warning:** Subqueries are computationally expensive. Use recording rules for frequent queries.

### _over_time Functions

Apply aggregations over a range vector:

| Function | Description |
|----------|-------------|
| \`avg_over_time(v[range])\` | Average of values in the range |
| \`min_over_time(v[range])\` | Minimum value in the range |
| \`max_over_time(v[range])\` | Maximum value in the range |
| \`sum_over_time(v[range])\` | Sum of values in the range |
| \`count_over_time(v[range])\` | Count of samples in the range |
| \`quantile_over_time(q, v[range])\` | Quantile q of values |
| \`stddev_over_time(v[range])\` | Standard deviation in the range |
| \`last_over_time(v[range])\` | Last value in the range |

\`\`\`promql
# Average memory over the last 30 minutes
avg_over_time(container_memory_usage_bytes[30m])

# Peak CPU in the last hour
max_over_time(node_cpu_seconds_total{mode="idle"}[1h])

# P95 latency over the last 10 minutes
quantile_over_time(0.95, http_request_duration_seconds[10m])
\`\`\`

### Histograms and histogram_quantile()

Prometheus histograms store counts in **cumulative buckets**:

\`\`\`promql
# Metrics generated by a histogram:
http_request_duration_seconds_bucket{le="0.1"}    # requests <= 100ms
http_request_duration_seconds_bucket{le="0.5"}    # requests <= 500ms
http_request_duration_seconds_bucket{le="1.0"}    # requests <= 1s
http_request_duration_seconds_bucket{le="+Inf"}   # all requests
http_request_duration_seconds_sum                   # total sum of durations
http_request_duration_seconds_count                 # total count
\`\`\`

#### Calculating Percentiles with histogram_quantile()
\`\`\`promql
# P99 latency
histogram_quantile(0.99,
  rate(http_request_duration_seconds_bucket[5m])
)

# P50 (median) by service
histogram_quantile(0.50,
  sum by(service, le) (rate(http_request_duration_seconds_bucket[5m]))
)

# Global P95
histogram_quantile(0.95,
  sum by(le) (rate(http_request_duration_seconds_bucket[5m]))
)
\`\`\`

> **Important:** Always apply \`rate()\` to buckets BEFORE \`histogram_quantile()\`. The \`le\` label must be preserved in \`sum by()\`.

#### Average Latency
\`\`\`promql
# Average = sum / count
rate(http_request_duration_seconds_sum[5m])
/
rate(http_request_duration_seconds_count[5m])
\`\`\`

### Recording Rules

Recording rules pre-compute expensive queries and save them as new metrics:

\`\`\`yaml
# prometheus-rules.yml
groups:
  - name: custom_rules
    interval: 30s
    rules:
      - record: job:http_requests:rate5m
        expr: sum by(job) (rate(http_requests_total[5m]))

      - record: instance:node_cpu:usage_percent
        expr: (1 - avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m]))) * 100

      - record: namespace:container_memory:sum_bytes
        expr: sum by(namespace) (container_memory_usage_bytes{container!=""})
\`\`\`

**Naming convention:** \`level:metric:operation\`
- \`job:http_requests:rate5m\` — grouped by job, http_requests metric, rate5m operation
- \`instance:node_cpu:usage_percent\` — per instance, cpu, usage percentage

### Label Functions

\`\`\`promql
# label_replace — create/modify labels
label_replace(up, "hostname", "$1", "instance", "(.*):.*")
# Extracts "hostname" from "instance" removing the port

# label_join — concatenate labels
label_join(up, "target_info", "-", "job", "instance")
# Creates label "target_info" = "job-instance"
\`\`\`

### Math and Time Functions

\`\`\`promql
# Round up
ceil(container_memory_usage_bytes / 1048576)  # MB rounded

# Round down
floor(node_filesystem_avail_bytes / 1073741824)  # GB

# Absolute value
abs(deriv(temperature_celsius[1h]))

# Clamp — limit between min and max
clamp(cpu_usage_percent, 0, 100)
clamp_min(metric, 0)   # don't allow negatives
clamp_max(metric, 100)  # limit to 100

# Timestamp of the last sample
timestamp(up)

# Derivative (rate of change of a gauge)
deriv(temperature_celsius[1h])

# Linear prediction (predict_linear)
predict_linear(node_filesystem_avail_bytes[6h], 3600*24)
# Predicts the value 24 hours from now based on the last 6 hours trend
\`\`\`

### predict_linear() for Capacity Planning

\`\`\`promql
# Predict when disk will be full
# If predict_linear returns a negative value, disk will be full before 24h
predict_linear(node_filesystem_avail_bytes{mountpoint="/"}[6h], 3600*24) < 0

# Predict available memory in 4 hours
predict_linear(node_memory_MemAvailable_bytes[2h], 3600*4)
\`\`\`

## Common Mistakes

1. **Forgetting \`le\` in sum for histogram_quantile()**: \`sum by(service) (rate(bucket[5m]))\` loses the \`le\` label and the function fails. Correct: \`sum by(service, le)\`.
2. **Not applying rate() before histogram_quantile()**: Buckets are cumulative counters — without rate(), values are meaningless for percentile calculation.
3. **Using subqueries unnecessarily**: Subqueries are expensive. If possible, create recording rules instead.
4. **Confusing group_left and group_right**: \`group_left\` means the left side (many) can have more series. The opposite side (one) must have at most one series per label combination.
5. **predict_linear with too short range**: If the trend is evaluated over just a few minutes, the prediction is unstable. Use at least 1-6 hours.
6. **Recording rules with non-standard names**: Use the \`level:metric:operation\` convention for organization.

## Killer.sh Style Challenge

**Scenario:** Your cluster has heavy traffic and you need to analyze latency patterns and predict capacity issues.

**Tasks:**
1. Calculate the P99 HTTP latency by service over the last 5 minutes
2. Create a query that predicts if any node's disk will fill up in the next 24 hours
3. Compare the current request rate with the average over the last 3 hours
4. Write a recording rule to pre-compute CPU usage per node

**Solutions:**
\`\`\`promql
# 1. P99 by service
histogram_quantile(0.99,
  sum by(service, le) (rate(http_request_duration_seconds_bucket[5m]))
)

# 2. Disk prediction (alert if negative = will fill up)
predict_linear(node_filesystem_avail_bytes{mountpoint="/"}[6h], 86400) < 0

# 3. Current requests vs 3-hour average
sum(rate(http_requests_total[5m]))
/
avg_over_time(sum(rate(http_requests_total[5m]))[3h:5m])

# 4. Recording rule
# record: instance:node_cpu:usage_percent
# expr: (1 - avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m]))) * 100
\`\`\`
`,
  quiz: [
    {
      question: 'In PromQL, what does the group_left clause do in a binary operation?',
      options: [
        'Groups results by the left side',
        'Indicates that the left side (many) can have more series than the right side (one) — many-to-one matching',
        'Filters only the series from the left operand',
        'Performs a LEFT JOIN like in SQL'
      ],
      correct: 1,
      explanation: 'group_left indicates many-to-one matching: the left side can have multiple series for each series on the right side. It is useful when you want to enrich metrics with metadata (e.g., adding info labels to usage metrics).',
      reference: 'Related concept: promql-basics — understand basic binary operations before advanced vector matching.'
    },
    {
      question: 'What is the correct way to calculate P95 latency using histogram_quantile()?',
      options: [
        'histogram_quantile(0.95, http_request_duration_seconds_bucket)',
        'histogram_quantile(0.95, sum by(le) (rate(http_request_duration_seconds_bucket[5m])))',
        'histogram_quantile(95, rate(http_request_duration_seconds_bucket[5m]))',
        'quantile(0.95, http_request_duration_seconds)'
      ],
      correct: 1,
      explanation: 'The correct form requires: (1) rate() applied to buckets, (2) sum by(le) to preserve the le label (essential for calculation), and (3) quantile between 0 and 1 (0.95, not 95).',
      reference: 'Related concept: prom-alerting — use percentiles in latency alerts (SLO/SLI).'
    },
    {
      question: 'What does the predict_linear() function do?',
      options: [
        'Calculates the linear average of a metric',
        'Predicts the future value of a gauge based on the trend over a period',
        'Creates a trend line on the graph',
        'Interpolates missing values in a time series'
      ],
      correct: 1,
      explanation: 'predict_linear(v[range], t) uses linear regression over the data in the range to predict what the metric value will be t seconds from now. It is commonly used for capacity planning (e.g., predicting when disk will fill up).',
      reference: 'Related concept: prom-alerting — predict_linear is ideal for proactive capacity alerts.'
    },
    {
      question: 'What is the naming convention for Prometheus recording rules?',
      options: [
        'metric_operation_interval (e.g., http_requests_rate_5m)',
        'level:metric:operation (e.g., job:http_requests:rate5m)',
        'freely_chosen_by_user',
        'recording_rule_query_name'
      ],
      correct: 1,
      explanation: 'The official convention is level:metric:operation. Level indicates the aggregation level (job, instance, namespace), metric indicates the original name, and operation describes the calculation (rate5m, sum, avg).',
      reference: 'Related concept: prom-alerting — recording rules are also used to simplify expressions in alerting rules.'
    },
    {
      question: 'What is the syntax for a PromQL subquery?',
      options: [
        'SELECT(query, range, resolution)',
        'subquery(query[range:resolution])',
        'query[range:resolution]',
        'query OVER(range STEP resolution)'
      ],
      correct: 2,
      explanation: 'The subquery syntax is: <instant_query>[<range>:<resolution>]. Example: rate(http_requests_total[5m])[30m:1m] evaluates rate() every 1 minute over the last 30 minutes, creating a range vector.',
      reference: 'Related concept: prom-alerting — subqueries can be useful in complex alerts, but prefer recording rules for performance.'
    },
    {
      question: 'What is the difference between on() and ignoring() in vector matching?',
      options: [
        'on() is faster than ignoring()',
        'on() specifies which labels to use for matching, ignoring() specifies which labels to ignore',
        'on() works with sum, ignoring() works with rate',
        'There is no difference, they are synonyms'
      ],
      correct: 1,
      explanation: 'on(labels) explicitly specifies which labels should be used to pair series (ignores all others). ignoring(labels) does the opposite: uses all labels EXCEPT the specified ones. They are analogous to by/without in aggregations.',
      reference: 'Related concept: promql-basics — by/without in aggregations follows the same logic.'
    },
    {
      question: 'Why is it important to apply rate() to buckets BEFORE histogram_quantile()?',
      options: [
        'Because histogram_quantile() only accepts instant vectors',
        'Because buckets are cumulative counters — rate() converts to rate, allowing correct percentile calculation',
        'Because without rate() the result is in bytes instead of seconds',
        'rate() is not necessary, it is just a best practice'
      ],
      correct: 1,
      explanation: 'Histogram buckets are cumulative counters (they only increase). Without rate(), histogram_quantile() would calculate the percentile of the total accumulated since the beginning, not the recent period. rate() transforms counters into per-second rates, allowing accurate percentile calculation for the interval.',
      reference: 'Related concept: prom-architecture — metric types and how counters work.'
    },
    {
      question: 'Which _over_time function would you use to find peak memory usage over the last 30 minutes?',
      options: [
        'avg_over_time(memory[30m])',
        'sum_over_time(memory[30m])',
        'max_over_time(memory[30m])',
        'peak_over_time(memory[30m])'
      ],
      correct: 2,
      explanation: 'max_over_time(v[range]) returns the highest value of each time series within the specified range. It is ideal for finding usage peaks. avg_over_time gives the average, sum_over_time the sum, and peak_over_time does not exist.',
      reference: 'Related concept: grafana-dashboards — use max_over_time in capacity panels to show peaks.'
    }
  ],
  flashcards: [
    {
      front: 'What is vector matching in PromQL and what are the types?',
      back: '**Vector matching** is how Prometheus pairs time series in binary operations (A op B).\n\nTypes:\n- **One-to-One**: each series from A pairs with exactly one from B (labels must match)\n- **Many-to-One** (group_left): multiple series from A pair with one from B\n- **One-to-Many** (group_right): one series from A pairs with multiple from B\n\nModifiers: on(labels) or ignoring(labels)'
    },
    {
      front: 'What is the subquery syntax and when should you use it?',
      back: '**Syntax:** instant_query[range:resolution]\n\nExample: avg_over_time(rate(x[5m])[1h:5m])\n- Evaluates rate(x[5m]) every 5 minutes\n- Over the last 60 minutes\n- Applies avg_over_time to the result\n\n**When to use:** When you need to apply _over_time functions to results of functions that return instant vectors.\n\n**Warning:** Subqueries are expensive — prefer recording rules for frequent queries.'
    },
    {
      front: 'How do you calculate percentiles with histogram_quantile()?',
      back: 'Required steps:\n1. Apply **rate()** to buckets (they are counters)\n2. **Preserve the le label** in sum by()\n3. Use quantile between 0 and 1\n\n```promql\nhistogram_quantile(0.99,\n  sum by(service, le) (\n    rate(http_request_duration_seconds_bucket[5m])\n  )\n)\n```\n\nFor average latency: rate(_sum[5m]) / rate(_count[5m])'
    },
    {
      front: 'What is the naming convention for recording rules?',
      back: 'Pattern: **level:metric:operation**\n\nExamples:\n- job:http_requests:rate5m\n- instance:node_cpu:usage_percent\n- namespace:container_memory:sum_bytes\n\n**level** indicates aggregation (job, instance, namespace)\n**metric** indicates the original name\n**operation** describes the applied calculation\n\nRecording rules are defined in separate YAML files and evaluated periodically.'
    },
    {
      front: 'What is predict_linear() used for?',
      back: '**predict_linear(v[range], t)** uses linear regression to predict the future value of a gauge.\n\nExamples:\n```promql\n# Will disk be full in 24h?\npredict_linear(node_filesystem_avail_bytes[6h], 86400) < 0\n\n# How much memory in 4h?\npredict_linear(node_memory_MemAvailable_bytes[2h], 14400)\n```\n\nRules:\n- Only works with gauges\n- Use 1-6h range for stable prediction\n- Ideal for proactive capacity alerts'
    },
    {
      front: 'What are the most important _over_time functions?',
      back: '- **avg_over_time(v[r])** — average\n- **max_over_time(v[r])** — peak\n- **min_over_time(v[r])** — minimum\n- **sum_over_time(v[r])** — sum\n- **count_over_time(v[r])** — sample count\n- **quantile_over_time(q, v[r])** — percentile\n- **stddev_over_time(v[r])** — standard deviation\n- **last_over_time(v[r])** — last value\n\nAll take range vectors from gauges (except count_over_time which works with any type).'
    },
    {
      front: 'What is the difference between on() and ignoring() in binary operations?',
      back: '**on(labels)** — uses ONLY the listed labels for pairing series\n**ignoring(labels)** — uses ALL labels EXCEPT the listed ones\n\nAnalogous to by/without in aggregations:\n- on() = by() (specifies what to include)\n- ignoring() = without() (specifies what to exclude)\n\nExample:\n```promql\nmetric_a / on(job) group_left metric_b\n# Pairs only by "job", allows many series in A\n```'
    },
    {
      front: 'How does label_replace() work in PromQL?',
      back: '**label_replace(v, dst_label, replacement, src_label, regex)**\n\nCreates or modifies labels based on regex:\n\n```promql\n# Extract hostname (without port) from instance\nlabel_replace(up, "hostname", "$1", "instance", "(.*):.*")\n# instance="10.0.1.5:9090" -> hostname="10.0.1.5"\n\n# Copy label\nlabel_replace(metric, "env", "$1", "namespace", "(.*)")\n```\n\nUseful for aligning labels from different metric sources before binary operations.'
    }
  ],
  lab: {
    scenario: 'You manage a cluster with heavy HTTP traffic and need to build advanced queries for performance analysis, capacity planning, and troubleshooting. The cluster has Prometheus with latency histograms, node_exporter metrics, and kube-state-metrics.',
    objective: 'Master vector matching, histogram_quantile(), subqueries, predict_linear(), and recording rules. By the end, you will have queries ready for advanced dashboards and proactive alerts.',
    duration: '25-35 minutes',
    steps: [
      {
        title: 'Vector Matching and Metric Enrichment',
        instruction: `Practice binary operations between metrics from different sources using on() and group_left.

\`\`\`promql
# Scenario: enrich CPU metrics with node info
# First, see the labels of each metric
node_cpu_seconds_total{mode="idle"}
kube_node_info

# Now combine using on() and group_left
avg by(node) (rate(node_cpu_seconds_total{mode="idle"}[5m]))
  * on(node) group_left(kernel_version)
  kube_node_info

# Calculate CPU usage percentage per node with role info
(1 - avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m]))) * 100
\`\`\`

Try different combinations of on() and ignoring().`,
        hints: [
          'If kube_node_info is not available, use any pair of metrics that share at least one label',
          'group_left allows copying extra labels from the "one" (right) side',
          'Check the labels of both metrics separately before combining'
        ],
        solution: `\`\`\`promql
# If you don't have kube_node_info, do vector matching with node metrics
# Total CPU per instance
sum by(instance) (rate(node_cpu_seconds_total{mode!="idle"}[5m]))
/
count by(instance) (node_cpu_seconds_total{mode="idle"})

# Use ignoring to ignore non-matching labels
sum by(instance) (rate(node_network_receive_bytes_total[5m]))
/ ignoring(device)
sum by(instance) (rate(node_network_transmit_bytes_total[5m]))
\`\`\``,
        verify: `\`\`\`bash
# Verify binary operation returns results
curl -s 'http://localhost:9090/api/v1/query?query=sum%20by(instance)(rate(node_cpu_seconds_total{mode!=%22idle%22}[5m]))' | jq '.data.result | length'
# Expected output: number > 0

# Verify vector matching works
curl -s 'http://localhost:9090/api/v1/query?query=count(up%20*%20on(instance)%20group_left%20up)' | jq '.data.result | length'
# Expected output: number > 0
\`\`\``
      },
      {
        title: 'Histograms and Latency Percentiles',
        instruction: `Calculate latency percentiles using histogram_quantile() with histogram buckets.

\`\`\`promql
# Check if there are histogram metrics
{__name__=~".*_bucket"}

# P50, P90, P99 global latency
histogram_quantile(0.50, sum by(le) (rate(http_request_duration_seconds_bucket[5m])))
histogram_quantile(0.90, sum by(le) (rate(http_request_duration_seconds_bucket[5m])))
histogram_quantile(0.99, sum by(le) (rate(http_request_duration_seconds_bucket[5m])))

# P95 by service (preserving service AND le labels)
histogram_quantile(0.95,
  sum by(service, le) (rate(http_request_duration_seconds_bucket[5m]))
)

# Average latency
rate(http_request_duration_seconds_sum[5m])
/
rate(http_request_duration_seconds_count[5m])
\`\`\`

Compare average latency with P99 — the difference reveals the presence of outliers.`,
        hints: [
          'If you don\'t have HTTP metrics, look for any metric with the _bucket suffix',
          'prometheus_http_request_duration_seconds_bucket is a Prometheus self-metric',
          'Always include "le" in sum by() when using histogram_quantile()'
        ],
        solution: `\`\`\`promql
# Use Prometheus self-metrics if no app metrics available
histogram_quantile(0.99,
  sum by(le) (rate(prometheus_http_request_duration_seconds_bucket[5m]))
)

# Average Prometheus latency
rate(prometheus_http_request_duration_seconds_sum[5m])
/
rate(prometheus_http_request_duration_seconds_count[5m])

# Compare P50 vs P99
histogram_quantile(0.50, sum by(le) (rate(prometheus_http_request_duration_seconds_bucket[5m])))
histogram_quantile(0.99, sum by(le) (rate(prometheus_http_request_duration_seconds_bucket[5m])))
\`\`\``,
        verify: `\`\`\`bash
# Verify bucket metrics exist
curl -s 'http://localhost:9090/api/v1/query?query=count({__name__=~".*_bucket"})' | jq '.data.result[0].value[1]'
# Expected output: number > 0

# Verify histogram_quantile returns a result
curl -s 'http://localhost:9090/api/v1/query?query=histogram_quantile(0.99,sum%20by(le)(rate(prometheus_http_request_duration_seconds_bucket[5m])))' | jq '.data.result | length'
# Expected output: number > 0
\`\`\``
      },
      {
        title: 'Subqueries and _over_time Functions',
        instruction: `Practice subqueries to analyze trends and variations over time.

\`\`\`promql
# Average CPU over 1 hour, evaluated every 5 minutes
avg_over_time(
  (1 - avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])))[1h:5m]
)

# Peak memory usage over the last 30 minutes
max_over_time(container_memory_usage_bytes{container!=""}[30m])

# CPU standard deviation (high variability = potential problems)
stddev_over_time(
  (avg by(instance) (rate(node_cpu_seconds_total{mode!="idle"}[5m])))[1h:5m]
)

# Count how many samples exist for a metric (diagnostic)
count_over_time(up[1h])
\`\`\``,
        hints: [
          'Subqueries use the [range:step] syntax after the inner query',
          'If the subquery is slow, consider creating a recording rule',
          'High stddev_over_time indicates an unstable metric'
        ],
        solution: `\`\`\`promql
# Average CPU over the last hour
avg_over_time(
  (1 - avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])))[1h:5m]
) * 100

# Peak vs average memory (indicates spikes)
max_over_time(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes[1h])
/
avg_over_time(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes[1h])

# Samples per hour — scrape diagnostic
count_over_time(up{job="kubernetes-nodes"}[1h])
\`\`\``,
        verify: `\`\`\`bash
# Verify subquery works
curl -s 'http://localhost:9090/api/v1/query?query=avg_over_time(up[1h:5m])' | jq '.data.result | length'
# Expected output: number > 0

# Verify sample count (expect ~240 for scrape_interval=15s over 1h)
curl -s 'http://localhost:9090/api/v1/query?query=count_over_time(up[1h])' | jq '.data.result[0].value[1]'
# Expected output: number > 100
\`\`\``
      },
      {
        title: 'Capacity Planning with predict_linear()',
        instruction: `Use predict_linear() to predict capacity issues before they happen.

\`\`\`promql
# Predict disk space 24 hours from now
predict_linear(node_filesystem_avail_bytes{mountpoint="/"}[6h], 86400)

# Will disk fill up in 24h? (negative value = yes)
predict_linear(node_filesystem_avail_bytes{mountpoint="/"}[6h], 86400) < 0

# Convert to GB for easier reading
predict_linear(node_filesystem_avail_bytes{mountpoint="/"}[6h], 86400) / 1024 / 1024 / 1024

# Predict available memory in 4 hours
predict_linear(node_memory_MemAvailable_bytes[2h], 14400) / 1024 / 1024 / 1024

# Compare predict_linear with current value
node_filesystem_avail_bytes{mountpoint="/"} / 1024/1024/1024
predict_linear(node_filesystem_avail_bytes{mountpoint="/"}[6h], 86400) / 1024/1024/1024
\`\`\``,
        hints: [
          'predict_linear only works with gauges (not counters)',
          'Use a range of at least 1-6h for stable prediction',
          'Negative value in disk prediction = disk will fill up before the specified time',
          '86400 = 24 hours in seconds, 14400 = 4 hours'
        ],
        solution: `\`\`\`promql
# Disk alert: will it fill up in 24h?
predict_linear(node_filesystem_avail_bytes{mountpoint="/", fstype!~"tmpfs|overlay"}[6h], 86400) < 0

# Disk prediction in GB per node
predict_linear(
  node_filesystem_avail_bytes{mountpoint="/", fstype!~"tmpfs|overlay"}[6h],
  86400
) / 1073741824

# Memory prediction in GB
predict_linear(node_memory_MemAvailable_bytes[4h], 14400) / 1073741824

# Deriv — see current rate of change
deriv(node_filesystem_avail_bytes{mountpoint="/"}[1h])
\`\`\``,
        verify: `\`\`\`bash
# Verify predict_linear returns a result
curl -s 'http://localhost:9090/api/v1/query?query=predict_linear(node_filesystem_avail_bytes{mountpoint="/"}[6h],86400)/1073741824' | jq '.data.result[0].value[1]'
# Expected output: number (predicted GB of free space in 24h)

# Verify deriv
curl -s 'http://localhost:9090/api/v1/query?query=deriv(node_memory_MemAvailable_bytes[1h])' | jq '.data.result | length'
# Expected output: number > 0
\`\`\``
      },
      {
        title: 'Recording Rules (Planning)',
        instruction: `Plan recording rules to optimize the most expensive queries you created in previous steps.

Create a recording rules file based on the queries you ran:

\`\`\`yaml
# /etc/prometheus/rules/recording_rules.yml
groups:
  - name: node_metrics
    interval: 30s
    rules:
      - record: instance:node_cpu:usage_percent
        expr: (1 - avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m]))) * 100

      - record: instance:node_memory:usage_percent
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100

      - record: instance:node_disk:avail_gb
        expr: node_filesystem_avail_bytes{mountpoint="/",fstype!~"tmpfs|overlay"} / 1073741824

  - name: http_metrics
    interval: 30s
    rules:
      - record: job:http_requests:rate5m
        expr: sum by(job) (rate(http_requests_total[5m]))

      - record: job:http_latency:p99_seconds
        expr: histogram_quantile(0.99, sum by(job, le) (rate(http_request_duration_seconds_bucket[5m])))
\`\`\`

Check the Prometheus configuration to load the rules file.`,
        hints: [
          'Recording rules use the level:metric:operation naming convention',
          'The evaluation interval should be less than or equal to the scrape_interval',
          'Check prometheus.yml for the rule_files path',
          'Restart or reload Prometheus after adding rules'
        ],
        solution: `\`\`\`bash
# Check rule_files configuration in prometheus.yml
grep -A5 "rule_files" /etc/prometheus/prometheus.yml

# Validate rules file syntax
promtool check rules /etc/prometheus/rules/recording_rules.yml

# Reload Prometheus without restarting
curl -X POST http://localhost:9090/-/reload

# Or send SIGHUP
kill -HUP $(pgrep prometheus)

# Verify rules are active
curl -s http://localhost:9090/api/v1/rules | jq '.data.groups[].rules[] | {name: .name, type: .type}'
\`\`\``,
        verify: `\`\`\`bash
# Verify promtool validates the rules
promtool check rules /etc/prometheus/rules/recording_rules.yml
# Expected output: SUCCESS

# Verify active rules after reload
curl -s http://localhost:9090/api/v1/rules | jq '.data.groups | length'
# Expected output: number > 0

# Verify recording rule generates metrics
curl -s 'http://localhost:9090/api/v1/query?query=instance:node_cpu:usage_percent' | jq '.data.result | length'
# Expected output: number > 0 (after waiting 1 evaluation cycle)
\`\`\``
      }
    ]
  },
  troubleshooting: [
    {
      title: 'histogram_quantile() returns NaN or Inf',
      difficulty: 'medium',
      symptom: 'When calculating percentiles with histogram_quantile(), the result is NaN (Not a Number) or +Inf.',
      diagnosis: `\`\`\`promql
# Check if there is data in the buckets
rate(http_request_duration_seconds_bucket[5m])

# Check if the "le" label is present
sum by(le) (rate(http_request_duration_seconds_bucket[5m]))

# Check the +Inf bucket
rate(http_request_duration_seconds_bucket{le="+Inf"}[5m])

# Check if count > 0
rate(http_request_duration_seconds_count[5m])
\`\`\``,
      solution: `**Causes of NaN:**
1. **No data in the range**: If rate() returns 0 for all buckets, there is no data to calculate the percentile.
2. **Missing le label**: If you used \`sum by(service)\` without including \`le\`, the function cannot calculate.
3. **Non-cumulative buckets**: histogram_quantile() assumes cumulative buckets (Prometheus default).

**Causes of +Inf:**
1. **Percentile above the highest bucket**: If P99 exceeds the highest bucket (e.g., le="10"), the result is +Inf.
2. **Poorly sized buckets**: The buckets don't cover the actual range of values.

**Solutions:**
\`\`\`promql
# Fix: include le in sum by
histogram_quantile(0.99,
  sum by(service, le) (rate(http_request_duration_seconds_bucket[5m]))
)

# If +Inf: add larger buckets in instrumentation
# In the application code, adjust the histogram buckets
\`\`\``
    },
    {
      title: 'Binary operation returns empty result (vector matching fails)',
      difficulty: 'hard',
      symptom: 'When dividing or multiplying two metrics, the result is empty even though both have data individually.',
      diagnosis: `\`\`\`promql
# Step 1: check labels of metric A
http_requests_total
# {instance="app:8080", job="myapp", method="GET"}

# Step 2: check labels of metric B
http_capacity_total
# {instance="app:8080", job="capacity"}

# Step 3: try the operation
http_requests_total / http_capacity_total
# Result: empty (labels "job" and "method" don't match)
\`\`\``,
      solution: `**The problem:** By default, binary operations require ALL labels to match on both sides. If a single label differs, there is no match.

**Solution 1 — Use on() for partial matching:**
\`\`\`promql
http_requests_total / on(instance) group_left http_capacity_total
# Matches only by "instance", ignores other labels
\`\`\`

**Solution 2 — Use ignoring():**
\`\`\`promql
http_requests_total / ignoring(method, job) http_capacity_total
# Ignores labels that differ
\`\`\`

**Solution 3 — Aggregate first:**
\`\`\`promql
sum by(instance) (http_requests_total) / sum by(instance) (http_capacity_total)
# Aggregates to common labels before dividing
\`\`\`

**Diagnostic tip:** Always compare the labels of both metrics side by side to identify differences.`
    },
    {
      title: 'Recording rules are not generating metrics',
      difficulty: 'medium',
      symptom: 'You created recording rules in Prometheus, reloaded the configuration, but the new metrics do not appear when querying.',
      diagnosis: `\`\`\`bash
# Check if Prometheus loaded the rules
curl -s http://localhost:9090/api/v1/rules | jq '.data.groups[] | {name: .name, rules: [.rules[].name]}'

# Check Prometheus logs for errors
kubectl logs -l app=prometheus --tail=50 | grep -i "rule\\|error"

# Validate file syntax
promtool check rules /etc/prometheus/rules/recording_rules.yml

# Check if rule_files is configured in prometheus.yml
grep "rule_files" /etc/prometheus/prometheus.yml
\`\`\``,
      solution: `**Common causes:**

1. **Path not included in rule_files:**
\`\`\`yaml
# prometheus.yml — ensure the path is correct
rule_files:
  - "/etc/prometheus/rules/*.yml"
\`\`\`

2. **Syntax error in rules file:**
\`\`\`bash
# Validate before applying
promtool check rules /etc/prometheus/rules/recording_rules.yml
\`\`\`

3. **Prometheus didn't reload:**
\`\`\`bash
# Reload via API
curl -X POST http://localhost:9090/-/reload

# Verify successful reload in logs
kubectl logs -l app=prometheus --tail=10 | grep "Completed loading"
\`\`\`

4. **Rule expression returns empty:**
\`\`\`promql
# Test the expression directly in the Prometheus UI
# If the base query returns no data, the recording rule won't generate metrics either
\`\`\`

5. **Wait for the evaluation interval:** After reload, the rule needs at least 1 cycle (interval) to generate the first metric.`
    }
  ]
};
